### PR TITLE
Add ClusterPreferredOwner resource

### PR DESCRIPTION
**Pull request by DdenBraver**
Adds the Cluster Preferred Owner DSC Resource.

* **ClusterGroup**: Cluster group name
* **ClusterName**: Cluster name
* **Nodes**: Selected cluster nodes.
* **ClusterResources**: Selected cluster resources
* **Ensure**: Whether an owner should be present or removed

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/13)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYr4N3TuqP5x1U0_X3:-KGYr4N3TuqP5x1U0_X4:1082553263) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/README.md#L37)):*
Can you include a link to MSDN documentation on the feature?

---

*[README.md, line 53 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGTflX7ASRgo4XwS-hV:-KGTflX7ASRgo4XwS-hW:-506912357) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/README.md#L53)):*
Please include a summary of changes in an unreleased version change per the [contribution guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request)

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 224 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYqvyc4ZLHkoNQkL7x:-KGYqvydJa4Hw6CXLTDh:2127475188) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L224)):*
Files must end with a new line.  See [Style Guidelines, General Rule, #5](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#general-rules)

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.schema.mof, line 5 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYlV-Tl6vwavIqxI8e:-KGYlV-Tl6vwavIqxI8f:160406948) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.schema.mof#L5)):*
for

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by DdenBraver** [comment]
*[README.md, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYr4N3TuqP5x1U0_X3:-KGZMIrB2yDRCdHEi4VS:-1592043751) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/README.md#L37)):*
I could not find any direct documentation on this feature, I did however find a msdn blog post.
If you like I could add this one instead: https://blogs.msdn.microsoft.com/clustering/2008/10/14/preferred-owners-in-a-cluster/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYr4N3TuqP5x1U0_X3:-KGdn2jQS95b8frVOqqX:-1800951950) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/README.md#L37)):*
Either the blog and/or the kb mentioned in the blog:
http://support.microsoft.com/kb/299631

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by DdenBraver** [comment]
*[README.md, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYr4N3TuqP5x1U0_X3:-KGlCfnGOikegq1dL1W3:-118459808) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/README.md#L37)):*
Added kb article to readme.md

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by DdenBraver** [comment]
*[README.md, line 53 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGTflX7ASRgo4XwS-hV:-KGlCl1JIv-P3P-BD1Ah:-2059588238) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/README.md#L53)):*
Included the new resource in the unreleased version change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by DdenBraver** [comment]
*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 224 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYqvyc4ZLHkoNQkL7x:-KGlCre6Bkv45aT-NJdn:2054900732) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L224)):*
Added a new line to the end of the script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by DdenBraver** [comment]
*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.schema.mof, line 5 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGYlV-Tl6vwavIqxI8e:-KGlCvt_GJHBImSJdVOY:248252362) ([raw file](https://github.com/powershell/xfailovercluster/blob/c189a3e88947b2befc75e8a07dfd956486e797f3/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.schema.mof#L5)):*
Removed additional spacings at the end of the schema.mof

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Comment by TravisEz13** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 37 \[r3\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/13#-KGnk6iQrpo_hjHO9rkK:-KGnk6iQrpo_hjHO9rkL:-442303403) ([raw file](https://github.com/powershell/xfailovercluster/blob/8da98c62068430aa81bb068da63c18f7318e15ad/README.md#L37)):*
should be `please [see kb299631.](http://support.microsoft.com/kb/299631)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/13)*

**Pull request merged**
