### PR TITLE
xFailOverCluster: Updating README.md, adding CHANGELOG.md, adding GitHub templates

### LINKED ISSUE #36: xClusterQuorum and xClusterDisk has the suffix '(Unreleased)' in README.me
They are released, so that should not be there?

https://github.com/PowerShell/xFailOverCluster#xclusterquorum-unreleased

### LINKED ISSUE #43: xFailOverCluster: Add a TOC for the resources to the README.md
Suggest we add a TOC for the resources to the README.md.

### LINKED ISSUE #44: xFailOverCluster: README.md is missing code of conduct.
We must add the 'code of conduct' to the README.md

### LINKED ISSUE #45: xFailOverCluster: Add GitHub templates
Add GitHub templates PULL_REQUEST_TEMPLATE, ISSUE_TEMPLATE and CONTRIBUTING.md to help contributors.

### LINKED ISSUE #48: xFailOverCluster: Split changelog to a separate file CHANGELOG.md
I suggest we split the chnage log to a separate file named CHANGELOG.md. It is easier to tell contributors to update that file, and don't have to browse past a list of resources.

### LINKED ISSUE #51: xClusterPreferredOwner: This resource is not listed in the README.md
xClusterPreferredOwner is not listed in the README.md

### LINKED ISSUE #56: xClusterNetwork: This resource is not listed in the README.md
xClusterNetworkis not listed in the README.md

### LINKED ISSUE #58: README.md: Parameters should list their class (data type) and type qualifier
I suggest to add all parameters like this.

* **[String] ClusterGroup** _(Key)_: Name of the cluster group.
* **[String] ClusterName** _(Key)_: Name of the cluster.
* **[String[]] Nodes** _(Required)_: The nodes to set as owners.
* **[String[]] ClusterResources** _(Write)_: The resources to set preferred owner on.
* **[String[]] Ensure** _(Write)_: If the preferred owners should be present or absent. { *Present* | Absent }

### LINKED ISSUE #62: xWaitForCluster: README.md list a parameter Credential which does not exist in the schema.mof
The parameters listed for the resource xWaitForCluster includes a parameter named Credential. It does not exist a parameter credential in the schema.mof of the resource.

This should be removed from the README.md

### PR DESCRIPTION
**Pull request by johlju**
- Changes to xFailOverCluster
  - Added 'Code of Conduct' text to the README.md (issue #44).
  - Added TOC for all resources in the README.md (issue #43).
  - Fixed typos and lint errors in README.md.
  - Fixed style issue in example in README.md.
  - Removed 'Unreleased' "tag" from the resources xClusterQuorum and xClusterDisk (issue #36)
  - Added new sections to each resource (Requirements, Parameters and Examples) in the README.md. Some does not yet have any examples, so they are set to 'None.'.
  - Added GitHub templates PULL\_REQUEST\_TEMPLATE, ISSUE_TEMPLATE and CONTRIBUTING.md (issue #45).
  - Split the change log from README.md to a seperate file CHANGELOG.md (issue #48).
  - Added the resource xClusterPreferredOwner to README.md (issue #51).
  - Added the resource xClusterNetwork to README.md (issue #56).
  - Removed Credential parameter from parameter list for xWaitForCluster. Parameter Credential does not exist in the schema.mof of the resource (issue #62).
  - Now all parameters in the README.md list their data type and type qualifier (issue #58.)
  - Added Import-DscResource to example in README.md.

Fixes #44 
Fixes #43 
Fixes #36 
Fixes #45 
Fixes #48 
Fixes #51 
Fixes #56
Fixes #62 
Fixes #58 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/60)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens or @RichardSiddaway Can anyone of you review this when you got a chance? 

I can send in an other PR that fixes the tests before we merge this one. But it's gonna take a few days (probably this weekend).

**Comment by bgelens** [comment]
Nice! I think I'll adopt some of those templates pretty soon!

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[README.md, line 28 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_P8r9WvV9QyYScsBc:-Km_P8r9WvV9QyYScsBd:buy0kgw) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L28)):*
> ```Markdown
> ## Change log
> 
> A full list of changes in each version can be found in the [change log](CHANGELOG.md).
> ```

Is this a general approach for all resources? 

---

*[README.md, line 124 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_PrvwDwzHO7CdvM9o:-Km_PrvwDwzHO7CdvM9p:bysj4bk) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L124)):*
> ```Markdown
> #### Parameters
> 
> * **IsSingleInstance** Always set to `Yes` to prevent multiple quorum settings per cluster.
> ```

Technically, this is actually to ensure this resource can only be used once in the configuration so ping/pong behavior is blocked.
A cluster can only have one quorum, so this is used to prevent on and on change behavior of the quorum.
(I do see it is a copy paste issue from your side so maybe an issue to change this later?)

---

*[README.md, line 125 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_RQzgM85Om7DcDHAL:-Km_RQzgM85Om7DcDHAM:bnzizxk) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L125)):*
> ```Markdown
> 
> * **IsSingleInstance** Always set to `Yes` to prevent multiple quorum settings per cluster.
> * **Type** Quorum type to use: *NodeMajority*, *NodeAndDiskMajority*, *NodeAndFileShareMajority*, *DiskOnly*.
> ```

Again, probably a fix for another issue but the resources above have the property types specified and these don't (not repeating this remark for other occurrences )

---

*[README.md, line 169 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_Rd3tdQZ3iMlS3Jqh:-Km_Rd3tdQZ3iMlS3Jqi:b-a96h28) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L169)):*
> ```Markdown
>         [ValidateNotNullorEmpty()]
>         [PsCredential]
>         $domainAdminCredential
> ```

Parameters should be PascalCase. https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-names-use-pascal-case

---

*[README.md, line 171 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_SSBtvoe5VXdHJWD_:-Km_SSBuHjhJgZ2x_f-B:b-3ld01x) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L171)):*
> ```Markdown
>         $domainAdminCredential
>     )
> ```

Missing an Import-DscResource of xFailOverCluster module. Example won't work

---

*[README.md, line 184 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_S1H8DaphZIcfh6tY:-Km_S1H8DaphZIcfh6tZ:b-nqh0) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L184)):*
> ```Markdown
>             Ensure = 'Present'
>             Name   = 'RSAT-Clustering-PowerShell'
> ```

Unnecessary white space (not repeating for other occurrences)

---

*[README.md, line 188 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_SqyKwE-U7EKlPOg5:-Km_SqyKwE-U7EKlPOg6:b-lartya) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L188)):*
> ```Markdown
>         }
> 
>         WindowsFeature RSATClusteringCmdInterface
> ```

Casing consistency on resource names?

---

*[README.md, line 193 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_T2peksLwbiHyX3jW:-Km_T2peksLwbiHyX3jX:b-bcmt92) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L193)):*
> ```Markdown
>             Name   = 'RSAT-Clustering-CmdInterface'
> 
>             DependsOn = '[WindowsFeature]RSATClusteringPowerShell'
> ```

'=' alignment ? (not repeating for other occurrences)

---

*[README.md, line 196 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_SxHNO5KOlnXJ9hyM:-Km_SxHNO5KOlnXJ9hyN:b-lartya) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L196)):*
> ```Markdown
>         }
> 
>         xCluster ensureCreated
> ```

Casing consistency on resource names?

---

*[README.md, line 202 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_UlvMyMN-LjIg7KSB:-Km_UlvMyMN-LjIg7KSC:b-m5jw60) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L202)):*
> ```Markdown
>             DomainAdministratorCredential = $domainAdminCredential
> 
>            DependsOn = “[WindowsFeature]RSATClusteringCmdInterface”
> ```

Indentation issue? (I see a couple but could be Reviewable?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-:-Km_VJXuFv0WCCGCt_8C:bjunb33)*

**Comment by johlju** [comment]
I will get to this changes later tonight.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[README.md, line 28 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_P8r9WvV9QyYScsBc:-Km_gU1EOFoXUq5JprHt:b-6y9iio) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L28)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Is this a general approach for all resources? 
</blockquote></details>

It is not. The PSDscResource uses README.md https://github.com/PowerShell/PSDscResources#versions

But the README.md tend to be long, and the version history is at the end, so it not easy to find. Also, I feel it's easier to tell contributors to 'update Unreleased section in the CHANGELOG.md', than 'update the Unreleased section under the Version section  at the bottom of the README.md' :)

If you feel we should keep it in README.md I happy to move it back. 

---

*[README.md, line 124 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_PrvwDwzHO7CdvM9o:-Km_hkP203VKqVyqkydu:bgsgzls) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L124)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Technically, this is actually to ensure this resource can only be used once in the configuration so ping/pong behavior is blocked.
A cluster can only have one quorum, so this is used to prevent on and on change behavior of the quorum.
(I do see it is a copy paste issue from your side so maybe an issue to change this later?)
</blockquote></details>

Actually I did not change that description, that was there prior to this PR. I did not even read it. :smile:  But I will update the description!

Also added an issue yesterday to fix descriptions; https://github.com/PowerShell/xFailOverCluster/issues/59. I will comment on that to verify so the descriptions are also correct. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-:-Km_i_da1ulAeozlUEu-:buacij)*

**Comment by bgelens** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[README.md, line 28 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_P8r9WvV9QyYScsBc:-Km_liEtDO4PUyibfsco:b-jgymbw) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L28)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

It is not. The PSDscResource uses README.md https://github.com/PowerShell/PSDscResources#versions

But the README.md tend to be long, and the version history is at the end, so it not easy to find. Also, I feel it's easier to tell contributors to 'update Unreleased section in the CHANGELOG.md', than 'update the Unreleased section under the Version section  at the bottom of the README.md' :)

If you feel we should keep it in README.md I happy to move it back. 
</blockquote></details>

I think it's a good idea to split up. Probably a good idea to raise an issue at DscResources to have this standardized?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/60)*

**Comment by johlju** [comment]
I added a bunch to this commit. Added comments to the example. Sorry for the additions, but hard not to try to improve something when you see something. :smile:

---

Review status: 3 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[README.md, line 28 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_P8r9WvV9QyYScsBc:-KmbHv5MllnVTDoqkZQM:bmp7peg) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L28)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

I think it's a good idea to split up. Probably a good idea to raise an issue at DscResources to have this standardized?
</blockquote></details>

Done. Brian has already done that; https://github.com/PowerShell/DscResources/issues/167

---

*[README.md, line 124 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_PrvwDwzHO7CdvM9o:-KmbIARO6Q6ZGlDpFc3a:b-17bj3r) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L124)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Actually I did not change that description, that was there prior to this PR. I did not even read it. :smile:  But I will update the description!

Also added an issue yesterday to fix descriptions; https://github.com/PowerShell/xFailOverCluster/issues/59. I will comment on that to verify so the descriptions are also correct. :smile: 
</blockquote></details>

Done. Used the text from the best practice article, which is also used in other resources in other modules.
https://msdn.microsoft.com/en-us/powershell/dsc/singleinstance

---

*[README.md, line 125 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_RQzgM85Om7DcDHAL:-KmbITB7B6NKYOmFuWw_:b-433hvb) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L125)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Again, probably a fix for another issue but the resources above have the property types specified and these don't (not repeating this remark for other occurrences )
</blockquote></details>

Done. Got to late yesterday, so submitted an issue, but I fixed now.

---

*[README.md, line 169 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_Rd3tdQZ3iMlS3Jqh:-KmbIec6bbLJEtLGObTS:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L169)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Parameters should be PascalCase. https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-names-use-pascal-case
</blockquote></details>

Done.

---

*[README.md, line 171 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_SSBtvoe5VXdHJWD_:-KmbIfTrAEv4jbGDsOwr:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L171)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Missing an Import-DscResource of xFailOverCluster module. Example won't work
</blockquote></details>

Done.

---

*[README.md, line 184 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_S1H8DaphZIcfh6tY:-KmbIhlHpL_p0Nm0EqpY:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L184)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Unnecessary white space (not repeating for other occurrences)
</blockquote></details>

Done.

---

*[README.md, line 188 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_SqyKwE-U7EKlPOg5:-KmbIiOVp_vgx7JlBS_q:byrzo74) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L188)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Casing consistency on resource names?
</blockquote></details>

Done. I over clarified them, let's try to avoid abbreviations.

---

*[README.md, line 193 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_T2peksLwbiHyX3jW:-KmbIrO6G7mR15XfAK58:bh0czuj) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L193)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

'=' alignment ? (not repeating for other occurrences)
</blockquote></details>

Done. I removed all aligned '=' since we don't have a guideline to either use or not use, and I feel most of the code in DSC Resource Kit does not align equal signs.

---

*[README.md, line 196 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_SxHNO5KOlnXJ9hyM:-KmbJGG4AecfBCn-k_ra:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L196)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Casing consistency on resource names?
</blockquote></details>

Done.

---

*[README.md, line 202 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-Km_UlvMyMN-LjIg7KSB:-KmbJJGN_bSK8f2ms0Ik:bhxqbow) ([raw file](https://github.com/powershell/xfailovercluster/blob/69515fc6c7a24ddf40757d35860e62ca83da412d/README.md#L202)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Indentation issue? (I see a couple but could be Reviewable?)
</blockquote></details>

Done. Reviewable was correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-:-KmbJl_KkwJO-CI6_1FW:bg44o5z)*

**Comment by johlju** [comment]
When PR #63 is merged, then we can merge this one (after I rebased this one). And after review is finished of course 😄

**Comment by bgelens** [comment]
:lgtm: Great job!!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-:-KmbpJux4tkm1lZRkHRE:boe5v17)*

**Comment by johlju** [comment]
@bgelens Rebased. Please verify in Reviewable that nothing changed. I did change the CHANGELOG.md to move the entries from the recently merged PR.

**Comment by bgelens** [comment]
:lgtm: Exactly as planned ;)

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/60#-:-Kmc794LqKMR6L2jpux2:b-k3sl2j)*

**Pull request merged**
