### PR TITLE
xFailOverCluster: Fixed failing tests in AppVeyor

### PR DESCRIPTION
**Pull request by johlju**
- Changes to xClusterPreferredOwner
  - Script Analyzer warnings have been fixed (issue #50). This also failed the tests for the resource.
- Changes to xClusterDisk
  - Fixed test that was failing in  AppVeyor (issue #55).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/63)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens If you have time to review this one. This fixes the tests failing in AppVeyor. Unfortunately the files contained a lot of spaces where there shouldn't so VSCode trimmed them. So there are more changes than I wanted. :/

**Comment by bgelens** [comment]
Some minor comments since you are on a roll already ;)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 40 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbckHyuaCfuSYLKI7b:-KmbckHyuaCfuSYLKI7c:b-elt9z6) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L40)):*
> ```PowerShell
> 
>         Write-Verbose -Message "Retrieving Owner information for Cluster Group $ClusterGroup"
>         (((Get-ClusterGroup -cluster $Clustername)| Where-Object {$_.name -like "$ClusterGroup"} | Get-ClusterOwnerNode).ownernodes).name
> ```

Parameter ClusterName has been fixed with correct PascalCase. Now the variable needs to fixed as well

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 47 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbejUXPPbmx7lRNKff:-KmbejUXPPbmx7lRNKfg:b-azlpcw) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L47)):*
> ```PowerShell
>             {
>                 Write-Verbose -Message "Retrieving Owner information for Cluster Resource $resource"
>                 (((Get-ClusterResource -cluster $Clustername)| Where-Object {$_.name -like "$resource"} | Get-ClusterOwnerNode).ownernodes).name
> ```

ClusterName

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 55 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-Kmben2LUCHUy3bxga7f:-Kmben2LUCHUy3bxga7g:b-azlpcw) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L55)):*
> ```PowerShell
>     $returnValue = @{
>         ClusterGroup = $ClusterGroup
>         Clustername = $Clustername
> ```

ClusterName

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 190 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-Kmbf4E9CwIQF91cxdtK:-Kmbf4E9CwIQF91cxdtL:b-62sjap) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L190)):*
> ```PowerShell
> 
>     if ($Ensure -eq 'Present')
>         {
> ```

Please correct indentation where applicable like here

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 210 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbfIc3Is2SZ3TPZCc9:-KmbfIc3Is2SZ3TPZCcA:bji28bi) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L210)):*
> ```PowerShell
> 
>     if ($Ensure -eq 'Absent')
>         {
> ```

and here

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbfmfLdXDzRaQflut1:-KmbfmfLdXDzRaQflut2:b-u6ntnf) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L87)):*
> ```PowerShell
> 
>         Mock -CommandName 'Get-ClusterParameter' -ParameterFilter { $Name -eq 'DiskIdGuid' } -MockWith {
>             #write-host $args.count -ForegroundColor Cyan
> ```

these can me removed I think

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 88 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbfqHteGn51lR9PLl4:-KmbfqHteGn51lR9PLl5:b-u6ntnf) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L88)):*
> ```PowerShell
>         Mock -CommandName 'Get-ClusterParameter' -ParameterFilter { $Name -eq 'DiskIdGuid' } -MockWith {
>             #write-host $args.count -ForegroundColor Cyan
>             #write-host $args -ForegroundColor Cyan
> ```

these can me removed I think

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 107 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbgGo5l3xL3tMi0HKF:-Kmbft_MvgPLKGpGbXgL:b-fnslh7) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L107)):*
> ```PowerShell
> 
>             It 'Returns a [System.Collection.Hashtable] type' {
> ```

Empty lines can be removed when they make not a lot of sense (multiple occasions, won't repeat remark)

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 121 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbgYzzM26j7PaUMlUG:-KmbgYzzM26j7PaUMlUH:b-uo64yj) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L121)):*
> ```PowerShell
>                 $Result.Label  | Should Be $TestParameter.Label
> 
>                 $Result -is [System.Collections.Hashtable] | Should Be $true
> ```

Not sure why this same test is in every It?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-:-KmbgprNxlYQglthmsWr:bbs6qsm)*

**Comment by johlju** [comment]
Well, since I'm on a roll I fixed more style issues. :wink: 
There is more to be done, but don't want to do too much at once.

---

Review status: 1 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 40 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbckHyuaCfuSYLKI7b:-Kmc-_1mArF5HZZXn7zx:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L40)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Parameter ClusterName has been fixed with correct PascalCase. Now the variable needs to fixed as well
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 47 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbejUXPPbmx7lRNKff:-Kmc-aj1TX4p9r48wdNp:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L47)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

ClusterName
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 55 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-Kmben2LUCHUy3bxga7f:-Kmc-k7MHWOqwvw7v8uF:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L55)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

ClusterName
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 190 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-Kmbf4E9CwIQF91cxdtK:-Kmc-qQnoILFzUZ3XrOf:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L190)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Please correct indentation where applicable like here
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 210 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbfIc3Is2SZ3TPZCc9:-Kmc-rEsNxoRavQuQoFB:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L210)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbfmfLdXDzRaQflut1:-Kmc-sFhhmfY2h5Gewj7:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L87)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

these can me removed I think
</blockquote></details>

Done.

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 88 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbfqHteGn51lR9PLl4:-Kmc-sc2D959wFd8GnIT:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L88)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

these can me removed I think
</blockquote></details>

Done.

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 107 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbgGo5l3xL3tMi0HKF:-Kmc-u03AWEYIrLXgA4H:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L107)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Empty lines can be removed when they make not a lot of sense (multiple occasions, won't repeat remark)
</blockquote></details>

Done.

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 121 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-KmbgYzzM26j7PaUMlUG:-Kmc-vDmrpcw3vApqSol:bpmfpl5) ([raw file](https://github.com/powershell/xfailovercluster/blob/07802e64ae2d1e165b538368cfecbc9f0e64b42d/Tests/MSFT_xClusterDisk.Tests.ps1#L121)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Not sure why this same test is in every It?
</blockquote></details>

Done. Cleaned up those. I think we need to look over these tests a bit later, because they are a combination of unit tests and integration tests. We can do that when we have added CodeCov. I'm hoping to do that this weekend.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-:-Kmc-QISeX1i6SxuI5Ua:bgb1ihe)*

**Comment by bgelens** [comment]
:lgtm: Well done sir!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/63#-:-Kmc1IAUCh3B_RwqO1zE:bzeiqlc)*

**Pull request merged**
