### PR TITLE
xFailOverCluster: Update Pester syntax to v4

### LINKED ISSUE #149: xSQLServer: Migrate Pester Test Syntax from v3 -> v4
**Details of the scenario you tried and the problem that is occurring:**
As of Pester v4 the syntax of the Should cmdlet has changed from Should Be to Should -Be.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by mnewswanger**
**Pull Request (PR) description**
Update Pester syntax to v4 flags

**This Pull Request (PR) fixes the following issues:**
Resolves #149

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/152)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome work on this one! Just one review comment in the CHANGELOG.md. 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/152#-Kwf4ecWPRNa4UZFu2jf:-Kwf4ecWPRNa4UZFu2jg:b-jbq0dl) ([raw file](https://github.com/powershell/xfailovercluster/blob/3ed323733a7750008295d5f7bf5b71e5db154002/CHANGELOG.md#L6)):*
> Updated Pester command flags to v4

Could we change this to be closer to the text in the issue? Maybe 'Update Pester syntax to v4'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/152#-:-Kwf5nSE0mTHPLbg4rKI:b-3vfnr9)*

**Comment by johlju** [comment]
@mnewswanger Could you please go into Reviewable and write 'Done' (or click the Done-button) on each comment you resolved. That will enable me to acknowledge (resolve) the comments. 
You find Reviewable if you clink on the big purple button in the PR description. Please write 'Done' on each comment (which saves the comment as draft), and then click Publish and that will publish all the comments as a single comment back to GitHub.

**Comment by mnewswanger** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/152#-Kwf4ecWPRNa4UZFu2jf:-KwjkI26SXCcugeF63c1:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/3ed323733a7750008295d5f7bf5b71e5db154002/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Updated Pester command flags to v4

Could we change this to be closer to the text in the issue? Maybe 'Update Pester syntax to v4'?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/152)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/152#-:-KwjyBVirOJGGtRcaMzZ:bnfp4nl)*

**Comment by johlju** [comment]
Thanks for this one!

**Pull request merged**
