### PR TITLE
Add xClusterDisk resource

### PR DESCRIPTION
**Pull request by claudiospizzi**
I've created a resource to manage cluster disks.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/9)

### CODE REVIEW

**Comment by TravisEz13** [comment]
It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

Please include a summary of changes in an unreleased version change per the [contribution guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request)

**Comment by TravisEz13** [comment]
If there is no update of the pull request within 7 days, we will close the pull request.  After that, if you have an update, feel free to reopen the pull request or a new pull request.  Please consider closing and re-opening when ready for review.

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/9)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/9#-KEcG7prxpWfaTihsSnM:-KEcG7prxpWfaTihsSnN:363346346) ([raw file](https://github.com/powershell/xfailovercluster/blob/cdf8a9a410f6fd9b555638005d1a5591488aa428/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L4)):*
It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/9)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 1 \[r3\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/9#-KFC8AjoKltT5CEM4j1-:-KFC8AjoKltT5CEM4j10:1146265129) ([raw file](https://github.com/powershell/xfailovercluster/blob/b1700536918858917a7d19676defce38000fb918/README.md#L1)):*
Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
[Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/9)*

**Comment by claudiospizzi** [comment]
I've merged my changes into the current dev branch. I had to add the following command to install the Failover Cluster module to be able to mock these cmdlets:
`Add-WindowsFeature -Name RSAT-Clustering-PowerShell`

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 15 \[r4\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/9#-KFpn4axwmcRkesQB9Is:-KFpn4axwmcRkesQB9It:-2108777607) ([raw file](https://github.com/powershell/xfailovercluster/blob/f37b917b011ba94b51e3b84817c855c0d4cdea62/Tests/MSFT_xClusterDisk.Tests.ps1#L15)):*
Should probably detect if the feature is there and

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/9)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/MSFT_xClusterDisk.Tests.ps1, line 15 \[r4\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/9#-KFpn4axwmcRkesQB9Is:-KFpnRHWQqohOTJK-XwI:-530416535) ([raw file](https://github.com/powershell/xfailovercluster/blob/f37b917b011ba94b51e3b84817c855c0d4cdea62/Tests/MSFT_xClusterDisk.Tests.ps1#L15)):*
Hit publish before I finished this, Should probably detect if the feature is there and skip this instead of using silently continue.  It's fairly slow on this cmdlet.  Could you file an issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/9)*

**Pull request merged**
