### PR TITLE
Addressing multiple minor issues

### PR DESCRIPTION
**Pull request by DdenBraver**
- Addressed #6 Wrong cmdlet used to get Cluster Address Value.
- Actually returning the hashtable now, so that Get-DscResource does not fail
- Fixed the outputtype in xCluster and xWaitforCluster resources

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/14)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 39 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/14#-KGyLK01K_gxRFGeiuS8:-KGyLK01K_gxRFGeiuS9:796640906) ([raw file](https://github.com/powershell/xfailovercluster/blob/c2ac04767f134afd5379d1999d513d8366ee4633/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L39)):*
I don't see existing test coverage for this function. The ask is not that you cover the entire resource, but just the functional changes you made.

It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 53 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/14#-KGyKwtl-lOLD8Jtt-R2:-KGyKwtl-lOLD8Jtt-R3:422879021) ([raw file](https://github.com/powershell/xfailovercluster/blob/c2ac04767f134afd5379d1999d513d8366ee4633/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L53)):*
Good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/14)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/14)*

**Comment by DdenBraver** [comment]
*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 39 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/14#-KGyLK01K_gxRFGeiuS8:-KH-523UvYJd-jJtTwLy:-1106678999) ([raw file](https://github.com/powershell/xfailovercluster/blob/c2ac04767f134afd5379d1999d513d8366ee4633/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L39)):*
I will see if I can add some basic test coverage for this resource in the upcoming week :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/14)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 39 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/14#-KGyLK01K_gxRFGeiuS8:-KH1M69mPr55ez9Vv3oh:-1046310707) ([raw file](https://github.com/powershell/xfailovercluster/blob/c2ac04767f134afd5379d1999d513d8366ee4633/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L39)):*
Thanks! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/14)*

**Comment by DdenBraver** [comment]
My apologies for the delay, for some reason this item was no longer on my backlog.
I just added some basic tests for the xCluster resource.

**Comment by TravisEz13** [comment]
Ok, Thanks for your contribution!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/14#-:-KLPYYvsOrF9Vh5XtVBs:-260444707)*

**Pull request merged**
