### PR TITLE
xFailOverCluster: Minor style changes and applied auto-formatting

### LINKED ISSUE #135: xFailOverCluster: Code clean-up
**Details of the scenario you tried and the problem that is occurring:**
There are still some code that is not aligned against the style guideline.

Known things that can be cleaned
- Unnecessary parenthesis is used around cmdlets
- Cmdlets are using positional parameters instead of named

This will be just a basic clean up for issues that was raised in PR's.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xCluster
  - Minor style changes.
- Changes to xClusterDisk
  - Minor style changes.
- Changes to xClusterNetwork
  - Minor style changes.
- Changes to xClusterPreferredOwner
  - Minor style changes.
- Changes to xClusterQuorum
  - Minor style changes.
- Changes to xWaitForCluster
  - Minor style changes.

**This Pull Request (PR) fixes the following issues:**
Fixes #135 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/136)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Do you mind looking this over? Minor style per your previous comment in a PR. Please comment on any other style issues. 😄

**Comment by PlagueHO** [comment]
@johlju - no worries! Checking it now!

**Comment by PlagueHO** [comment]
All looks good - no blocking issues. Just a query about the alignment. Feel free to merge if you're happy with alignment.

:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 100 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-Kq6uiulktxwNMFCXffj:-Kq6uium_SCHzrEtpdRV:bh4ldkc) ([raw file](https://github.com/powershell/xfailovercluster/blob/f97b1f105dc1b77ef841f54ef1c48d3cbcb46535/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L100)):*
> ```PowerShell
> 
>             $diskResource = Get-ClusterResource |
>                                 Where-Object -FilterScript { $_.ResourceType -eq 'Physical Disk' } |
> ```

Non-blocking, but shouldn't the alignment of this line be 4 spaces in from ```$diskResource```? I'd assume this is what the VS Code autoformatting would set it to?

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 119 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-Kq6urOFZmf3joOpMGtO:-Kq6urOFZmf3joOpMGtP:bh4ldkc) ([raw file](https://github.com/powershell/xfailovercluster/blob/f97b1f105dc1b77ef841f54ef1c48d3cbcb46535/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L119)):*
> ```PowerShell
> 
>             $diskResource = Get-ClusterResource |
>                                 Where-Object -FilterScript { $_.ResourceType -eq 'Physical Disk' } |
> ```

Non-blocking, but shouldn't the alignment of this line be 4 spaces in from ```$diskResource```? I'd assume this is what the VS Code autoformatting would set it to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-:-Kq6v54m6og7u-YIbnI6:blt4co2)*

**Comment by johlju** [comment]
I run auto-formatting on every file in the repo. So that got changes in a bunch of files. :disappointed:  Now I feel like you :grin: It's looking like one of your PR's :smile: 

---

Review status: 0 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 100 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-Kq6uiulktxwNMFCXffj:-Kq6ybdZsvbpfPm7lgGa:blpretp) ([raw file](https://github.com/powershell/xfailovercluster/blob/f97b1f105dc1b77ef841f54ef1c48d3cbcb46535/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L100)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking, but shouldn't the alignment of this line be 4 spaces in from ```$diskResource```? I'd assume this is what the VS Code autoformatting would set it to?
</blockquote></details>

Done.

Actually, auto-formatting didn't want to move it back, so I moved it manually :smile: 

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 119 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-Kq6urOFZmf3joOpMGtO:-Kq6yqF10aXhupuk4E-q:blpretp) ([raw file](https://github.com/powershell/xfailovercluster/blob/f97b1f105dc1b77ef841f54ef1c48d3cbcb46535/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L119)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking, but shouldn't the alignment of this line be 4 spaces in from ```$diskResource```? I'd assume this is what the VS Code autoformatting would set it to?
</blockquote></details>

Done.

Actually, auto-formatting didn't want to move it back, so I moved it manually :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-:-Kq6yrQMctUqxDscRkrF:b-il98l6)*

**Comment by johlju** [comment]
@PlagueHO Could you review this one again when you have a chance? Sorry for all the new files 😞 But just as well get it out of the way directly. 😄

**Comment by PlagueHO** [comment]
@Johlju - haha LOL :grin: Yep - I do love to auto format all the things with many files being changed at once. I'm trying to be a bit more thoughtful now :grin: 

But I'm definitely OK with mass white space corrections because they only get done once and they're trivial to review with reviewable.

:lgtm:

---

Reviewed 24 of 24 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 100 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-Kq6uiulktxwNMFCXffj:-KqA77l8JWmYwwSu0WB_:b-3e5svx) ([raw file](https://github.com/powershell/xfailovercluster/blob/f97b1f105dc1b77ef841f54ef1c48d3cbcb46535/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L100)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.

Actually, auto-formatting didn't want to move it back, so I moved it manually :smile: 
</blockquote></details>

No worries! As long as auto-formatting keep it in place now :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/136#-:-KqA7NP_OaknhhNuzSQF:b-diijyx)*

**Pull request merged**
