### PR TITLE
xFailOverCluster: Added CodeCov plus Opt-in for common tests

### LINKED ISSUE #41: xFailOverCluster: Add CodeCov and make sure this module opt-in for the common tests that could be used
Suggest we add CodeCov to this module, and make sure this module opt-in for the common tests that could be used.

### LINKED ISSUE #42: xFailOverCluster: Add the examples in the README.md to Examples folder
Suggest that we add the examples in the README.md to Examples folder.

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xFailOverCluster
  - Added CodeCov and opt-in for all common tests (issue #41).
  - Added CodeCov badge to README.md
  - Fixed lint rule MD013 in CHANGELOG.md.
  - Fixed lint rule MD013 in README.md.
  - Fixed lint rule MD024 in README.md.
  - Fixed lint rule MD032 in README.md.
  - Removed example from README.md (issue #42).
  - Fixed typo in filename for ISSUE\_TEMPLATE. Was 'ISSUE\_TEMPLATE', now it is
    correctly 'ISSUE\_TEMPLATE.md'.
  - Changed appveyor.yml to use the new default test framework in the AppVeyor
    module in DscResource.Tests (AppVeyor.psm1).
- Changes to xCluster
  - Added examples
    - 1-CreateFirstNodeOfAFailoverCluster.ps1
    - 2-JoinAdditionalNodeToFailoverCluster.ps1
    - 3-CreateFailoverClusterWithTwoNodes.ps1 (this is the example from README.md)
  - Fixed typo in xCluster parameter description.
  - Added links to examples from README.md
- Changes to xWaitForCluster
  - Added example
    - 1-WaitForFailoverClusterToBePresent.ps1
  - Added link to example from README.md

**This Pull Request (PR) fixes the following issues:**
Fixes #41 
Fixes #42 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/65)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens Would you mind reviewing this one when you got a chance. 😄

**Comment by bgelens** [comment]
Done. Sorry for the delay! Not had a lot of time this weekend :)

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 3 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0acjOltu-kq54Eqp1:-Kn0acjOltu-kq54Eqp2:bmhgt8m) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/.gitignore#L3)):*
> ```
> DSCResource.Tests
> .vs
> .vscode
> ```

Won't this make adding the vscode style rules difficult in the future?

---

*[appveyor.yml, line 7 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0bY_FQDepte06o54X:-Kn0bY_FQDepte06o54Y:b5hrxo9) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/appveyor.yml#L7)):*
> ```YAML
> install:
>     - git clone https://github.com/PowerShell/DscResource.Tests
> ```

This is not stated on your PR description is it? 
Is this a new appveyor.yml default (i'm unfamiliar with it so sorry to ask)

---

*[CHANGELOG.md, line 51 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0buoiFP1Uotx6zv6y:-Kn0buoiFP1Uotx6zv6z:b-fd5khn) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/CHANGELOG.md#L51)):*
> ```Markdown
>   - Added example
>     - 1-WaitForFailoverClusterToBePresent.ps1
>   - Added link to example from README.md
> ```

Not sure if it's worth mentioning, but the changes to appveyor.yml are not in here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-:-Kn0ceOzSPkUvYTyhODk:b-9tmeeo)*

**Comment by johlju** [comment]
No worries :) I get this comments fixed.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 3 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0acjOltu-kq54Eqp1:-Kn0khA7OJao98b8hNZv:b-ryqjeq) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/.gitignore#L3)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Won't this make adding the vscode style rules difficult in the future?
</blockquote></details>

Not difficult. To change, you have to do the following

1. Change for example .vscode\settings.json
1. Remove .vscode from .gitignore
1. Commit
1. Add back .vscode to .gitignore.
1. Commit
1. Push

The downside not to have this in the .gitignore file is that we would get a lot of .vscode files in the PR's that we didn't want.

---

*[appveyor.yml, line 7 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0bY_FQDepte06o54X:-Kn0lSnJ0Fh0kQP4eFyX:b-ikz66q) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/appveyor.yml#L7)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

This is not stated on your PR description is it? 
Is this a new appveyor.yml default (i'm unfamiliar with it so sorry to ask)
</blockquote></details>

Fixing the PR description.

Yes, PSDscResources uses this, so this is the new default. All repos should change to this, or to the "Harness" model that for example SharePointDsc is using which also allows "auto" Wiki documentation. But then the folder structure need to change as well. "Harness" is not the default. 
Read more about it here: https://github.com/PowerShell/DscResource.Tests#example-usage-of-dscresourcetests-in-appveyoryml
And Daniel and Brian has best knowledge of the "Harness" model.

---

*[CHANGELOG.md, line 51 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0buoiFP1Uotx6zv6y:-Kn0motJgC5q2wTQU2cx:b-nq9abe) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/CHANGELOG.md#L51)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Not sure if it's worth mentioning, but the changes to appveyor.yml are not in here
</blockquote></details>

Yes, absolutely. Fixing that :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-:-Kn0mvODsOEMra7lDBkv:btzic4b)*

**Comment by johlju** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 3 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0acjOltu-kq54Eqp1:-Kn0p8ocDpqEJtd3GOWQ:b-puatdj) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/.gitignore#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not difficult. To change, you have to do the following

1. Change for example .vscode\settings.json
1. Remove .vscode from .gitignore
1. Commit
1. Add back .vscode to .gitignore.
1. Commit
1. Push

The downside not to have this in the .gitignore file is that we would get a lot of .vscode files in the PR's that we didn't want.
</blockquote></details>

Done. Let me know if you want me to exclude it.

---

*[appveyor.yml, line 7 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0bY_FQDepte06o54X:-Kn0p3hXTajLqGu4mcRH:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/appveyor.yml#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Fixing the PR description.

Yes, PSDscResources uses this, so this is the new default. All repos should change to this, or to the "Harness" model that for example SharePointDsc is using which also allows "auto" Wiki documentation. But then the folder structure need to change as well. "Harness" is not the default. 
Read more about it here: https://github.com/PowerShell/DscResource.Tests#example-usage-of-dscresourcetests-in-appveyoryml
And Daniel and Brian has best knowledge of the "Harness" model.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 51 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0buoiFP1Uotx6zv6y:-Kn0p1ehIXmdanectD3I:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/CHANGELOG.md#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yes, absolutely. Fixing that :smile: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/65)*

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitignore, line 3 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-Kn0acjOltu-kq54Eqp1:-Kn0pihPKvTFUIjs9BHK:besfnlg) ([raw file](https://github.com/powershell/xfailovercluster/blob/413c4bcd2ab0e2fbdd12b008ceae36adf0ca4753/.gitignore#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Let me know if you want me to exclude it.
</blockquote></details>

OK No I'm fine with the inclusion. Just wanted to check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/65#-:-Kn0q5o6T-iDbg9hWPQv:bnfp4nl)*

**Comment by johlju** [comment]
@bgelens btw, don't be sorry for asking. Happy to answer any questions. 😄

**Comment by bgelens** [comment]
Just being polite :wink:

**Comment by johlju** [comment]
Okay good 😉 

Merging this one.

**Pull request merged**
