### PR TITLE
xClusterResourceProperties: Adding DSC resource to configure cluster resource properties

### PR DESCRIPTION
**Pull request by jmos5156**
This resource allows a cluster resource to be configured with properties such as
RestartAction
AutoFailback
FailoverThreshold
and more

**Pull Request (PR) description**
This resource allows a cluster resource to be configured with properties such as
RestartAction
AutoFailback
FailoverThreshold
and more

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/161)

### CODE REVIEW

**Comment by johlju** [comment]
@jmos5156 Could you please add unit tests to this?

**Comment by johlju** [comment]
Also add this resource to README.md.

**Comment by johlju** [comment]
Thanks for sending in these to this repository. Please add tests, update README.md and add an entry to the CHANGELOG.md. After that I can review these. :)

**Comment by johlju** [comment]
@jmos5156 Let me know if you need any help with this PR.

**Comment by jmos5156** [comment]
Hi johlju Any hlp greatly appreciated.. A bit new to this whole process... I do have some updates

**Comment by johlju** [comment]
@jmos5156 Sorry for not responding for so long. 😞  I will be happy to help you get this PR over the finish line. I would like to see unit tests added to this PR. So these changes are tested. Do you think that is something you can look into? If you are new to unit tests you can look at this as an example https://github.com/PowerShell/xFailOverCluster/blob/dev/Tests/Unit/MSFT_xClusterProperty.Tests.ps1.
Let me know if you want any more help, and I will make sure to answer fast in the future.

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by johlju** [comment]
Closing this PR due to inactivity. If there are someone who wants to work on this issue or PR please open a new PR.

**Pull request closed without merging**
