### PR TITLE
xFailOverCluster: Added VS Code workspace settings file

### LINKED ISSUE #67: xFailOverCluster: Add VS Code workspace settings file with settings matching style guideline
**Details of the scenario you tried and the problem that is occurring:**
I suggest we add a VS Code workspace setting file with the following settings:

```
// Place your settings in this file to overwrite default and user settings.
{
    "powershell.codeFormatting.openBraceOnSameLine": false,
    "powershell.codeFormatting.newLineAfterOpenBrace": false,
    "powershell.codeFormatting.newLineAfterCloseBrace": true,
    "powershell.codeFormatting.whitespaceBeforeOpenBrace": true,
    "powershell.codeFormatting.whitespaceBeforeOpenParen": true,
    "powershell.codeFormatting.whitespaceAroundOperator": true,
    "powershell.codeFormatting.whitespaceAfterSeparator": true,
    "powershell.codeFormatting.ignoreOneLineBlock": false,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true
}
```
This is discussed here https://github.com/PowerShell/DscResources/issues/284.

That will make it possible inside VS Code to press <kbd>SHIFT</kbd>+<kbd>ALT</kbd>+<kbd>F</kbd> or press <kbd>F1</kbd> and choose 'Format document' in the list. The PowerShell code will then be formatted according to the Style Guideline (although maybe not complete, but would help a lot).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xFailOverCluster
  - Added VS Code workspace settings file with formatting settings matching the
    Style Guideline (issue #67). That will make it possible inside VS Code to
    press SHIFT+ALT+F, or press F1 and choose 'Format document' in the list. The
    PowerShell code will then be formatted according to the Style Guideline
    (although maybe not complete, but would help a long way).

**This Pull Request (PR) fixes the following issues:**
Fixes #67 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/68)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens If you want to review this one whenever you have a chance. No hurry. 

Btw. It seems that we can't protect our self from changes to the settings.json file with the .gitignore file. Once a file is indexed it .gitignore will, well, ignore it ;) So if a contributor makes a change to the settings.json it will be included into the PR unfortunately (and we have to handle that in the review). But all new files in the .vscode folder will be ignore as long as .vscode is in the .gitignore file.

**Comment by johlju** [comment]
@bgelens Updated this PR according to https://github.com/PowerShell/DscResources/issues/284#issuecomment-312422210

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.vscode/settings.json, line 1 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/68#-Ko7RPhH61fqOK8wm3eU:-Ko7RPhH61fqOK8wm3eV:b-swm4zt) ([raw file](https://github.com/powershell/xfailovercluster/blob/065a57d0bff3093ba0169d57b0f60ced89a20365/.vscode/settings.json#L1)):*
> ```JSON
> // Place your settings in this file to overwrite default and user settings.
> ```

OK. Personally I would remove this comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/68#-:-Ko7Rcjk2K0Wb7L1eoF2:bnfp4nl)*

**Comment by johlju** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.vscode/settings.json, line 1 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/68#-Ko7RPhH61fqOK8wm3eU:-Ko7SbBmt1q86PAFq9Vb:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/065a57d0bff3093ba0169d57b0f60ced89a20365/.vscode/settings.json#L1)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

OK. Personally I would remove this comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/68)*

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/68)*

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/68#-:-Ko7SqOez-RYN0SfeF-1:bnfp4nl)*

**Pull request merged**
