### PR TITLE
xClusterNetwork: Enabled localization

### LINKED ISSUE #85: xClusterNetwork: Localization should change to align with HQRM modules
**Details of the scenario you tried and the problem that is occurring:**
Resource should use the same method of localization as HQRM modules (PSDscResource).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xClusterNetwork
  - Enabled localization for all strings ([issue #85](https://github.com/PowerShell/xFailOverCluster/issues/85)).
  - Fixed typo in parameter descriptions in comment-based help.

**This Pull Request (PR) fixes the following issues:**
Fixes #85 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/116)

### CODE REVIEW

**Comment by johlju** [comment]
Closing and reopening to kick of AppVeyor tests. This after AppVeyor deployed a temporary workaround.

**Comment by johlju** [comment]
@PlagueHO do you have time to review this one for me? No hurry.

**Comment by PlagueHO** [comment]
No problem @johlju - will review tomorrow night after work (bed time now!)

**Comment by PlagueHO** [comment]
Just a couple of corrections! Nothing major.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 119 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/116#-KpssZfdQ8_IHxmlaO5X:-KpssZfdQ8_IHxmlaO5Y:b-adcs0p) ([raw file](https://github.com/powershell/xfailovercluster/blob/cb4e5e4a210f82d4115cfa7351e38caae271e59c/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L119)):*
> ```PowerShell
>     if ($PSBoundParameters.ContainsKey('Role') -and $getTargetResourceResult.Role -ne $Role)
>     {
>         Write-Verbose -Message ($script:localizedData.ChangeNetworkName -f $Address, $AddressMask, $Role)
> ```

This should be ChangeNetworkRole

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 130 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/116#-KpssdbDD5_f5xrY5zY2:-KpssdbEg6T_QfrC4Hrr:b-oowvrz) ([raw file](https://github.com/powershell/xfailovercluster/blob/cb4e5e4a210f82d4115cfa7351e38caae271e59c/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L130)):*
> ```PowerShell
>     if ($PSBoundParameters.ContainsKey('Metric') -and $getTargetResourceResult.Metric -ne $Metric)
>     {
>         Write-Verbose -Message ($script:localizedData.ChangeNetworkName -f $Address, $AddressMask, $Metric)
> ```

This should be ChangeNetworkMetric

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/116#-:-KpssiORis9wIkvHo1VG:bab1pd1)*

**Comment by johlju** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 119 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/116#-KpssZfdQ8_IHxmlaO5X:-KptbTQhLoXDuQvikJb7:b-t7szbj) ([raw file](https://github.com/powershell/xfailovercluster/blob/cb4e5e4a210f82d4115cfa7351e38caae271e59c/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L119)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This should be ChangeNetworkRole
</blockquote></details>

Done. Good catch! Copy/paste error

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 130 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/116#-KpssdbDD5_f5xrY5zY2:-Kptb_UpDQA0aVM9luf6:b-t7szbj) ([raw file](https://github.com/powershell/xfailovercluster/blob/cb4e5e4a210f82d4115cfa7351e38caae271e59c/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L130)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This should be ChangeNetworkMetric
</blockquote></details>

Done. Good catch! Copy/paste error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/116)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/116#-:-Kpxs7B3dUW6PzJTpjMU:bnfp4nl)*

**Pull request merged**
