### PR TITLE
Added '-NoStorage' to add-clusternode cmdlet - fixed issue #4

### PR DESCRIPTION
**Pull request by JasonMorgan**
Added the '-NoStorage' switch to ensure that disks do not automatically get added to the cluster when adding nodes.

### CODE REVIEW

**Comment by TravisEz13** [comment]
Can you add a simple unit test that verifies that when this function is called that the -NoStorage switch is used?  It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

You'll need to mock Add-clusternode with a [parameterfilter](https://github.com/pester/Pester/wiki/Mock#example-2) 

Then [assert-mockcalled](https://github.com/pester/Pester/wiki/Assert-MockCalled)

And here is a [real life example test from a DSC resource](https://github.com/PowerShell/xActiveDirectory/blob/dev/Tests/xADGroup.Tests.ps1#L265)

**Comment by JasonMorgan** [comment]
So you don't actually have any tests for the resource yet.  Do you want me to create them?

I can do that but this PR was just to fix the obvious problem with xFailoverCluster.  I'd be happy to do another PR to add tests to the module, it just seems like the 2 issues are logically separate.

**Comment by TravisEz13** [comment]
@JasonMorgan I understand there are no existing tests and it's unfortunate the original author(s) didn't provide them, but in order to keep the project quality up we have set the following  [Contribution Guidelines about Adding test coverage for DSC resources,](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)   which require a minimum level of test coverage for any change.  Including this language:
> It is required that you provide adequate coverage for the code you change.

I believe this would be satisfied if you either:

1.  provided a PR with general tests before this PR, then updated or add a test in this PR to ensure this change does not regress
2. provide a one or more tests in this PR that ensures that this change does not regress.

**Comment by TravisEz13** [comment]
@JasonMorgan Please follow up with tests.  I'm going to merge this before it has a conflict and there is no real logic change here.

Thanks

**Pull request merged**
