### PR TITLE
xCluster: Allow cluster to be assigned IP address from a DHCP

### LINKED ISSUE #28: xCluster`s Get function will fail
xCluster module`s get function will fail, due to using Get-ClusterGroup Cmdlet.
> $address = Get-ClusterGroup -Cluster $Name -Name "Cluster IP Address" | Get-ClusterParameter "Address"

"Cluster IP Address" is not Cluster Group, it is Cluster Resource. We should use Get-ClusterResource Cmdlet.

### LINKED ISSUE #109: xCluster: Support DHCP addresses for clusters
Should support more than just a static IP.

### PR DESCRIPTION
**Pull request by wasabii**
**Pull Request (PR) description**
- Changes to xCluster
  - Allow cluster to be assigned IP address from a DHCP (issue #109).
    When parameter StaticIPAddress is not specified then cluster will be configured
    to use IP address from a DHCP.

**This Pull Request (PR) fixes the following issues:**
Fixes #109 
Fixes #28 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/113)

### CODE REVIEW

**Comment by johlju** [comment]
@wasabii Thanks for sending in this pull request. Could you please add a test for this change as well?

**Comment by wasabii** [comment]
Trying to figure out how. First time messing with this test framework.

**Comment by johlju** [comment]
No worries, there is no hurry. Let me know if you need any assistance in any way. :)

**Comment by wasabii** [comment]
Yeah. I'd appreciate some help. Where do you think these should go? Part of me says every existing test should simply be run with StaticIPAddress as unspecified. So, like, somehow duplicating the entire thing.

**Comment by johlju** [comment]
I don't think you need to run every existing test twice. But at least add one more test for each function (Get-/Set-/Test-TargetResource) where you remove the StaticIPAddress from the parameter list.

It would also be good that for the Set-TargetResource the mock for New-Cluster should have a new ParameterFilter `$StaticIpAddress -eq $null` for the new test in Set-TargetResource, and for one of the old test it should have ParameterFilter `$StaticIpAddress -ne $null`. And then you Assert-MockCalled with the respectively ParameterFilter so you know that the correct mock was called and not the other.

**Comment by johlju** [comment]
@wasabii I updated the PR description with the correct template. Let me know if you need further help with the tests. 😄

**Comment by johlju** [comment]
@wasabii You need to rebase (`git rebase`) this one again, both because new PR was merged and a new release was done.
How's it going with the test? Need any more help?

**Comment by johlju** [comment]
@wasabii are you still working on this? Let me know if you can't work on this anymore. :)

**Comment by wasabii** [comment]
It might be a long time before I get back to it. Was pulled off onto other tasks.

**Comment by johlju** [comment]
Would you mind checking "Allow edits from maintainers" to the right here? The I could bring this to the finish line for you.

**Comment by johlju** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 57 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/113#-KtSEqVAYnEAlv1bi3yj:-KtSEqVAYnEAlv1bi3yk:bc37zb7) ([raw file](https://github.com/powershell/xfailovercluster/blob/d471dab4d0d07cb9cf30249ef5623a67c113d8c0/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L57)):*
> ```PowerShell
>         }
> 
>         $address = Get-ClusterGroup -Cluster $Name -Name 'Cluster IP Address' -ErrorAction SilentlyContinue | Get-ClusterParameter -Name 'Address' -ErrorAction SilentlyContinue
> ```

Isn't possible to return the assigned IP-address here from DHCP? That could be of interest when running Get-DscConfiguration.
Uncertain if this change does just that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113)*

**Comment by johlju** [comment]
@wasabii added tests for this change. Just one question, that I need to verify, unless you have an answer, before I can merge this one,

**Comment by johlju** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 57 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/113#-KtSEqVAYnEAlv1bi3yj:-KtUjsW4ecxwTCo8kTSJ:b5d2kng) ([raw file](https://github.com/powershell/xfailovercluster/blob/d471dab4d0d07cb9cf30249ef5623a67c113d8c0/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L57)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Isn't possible to return the assigned IP-address here from DHCP? That could be of interest when running Get-DscConfiguration.
Uncertain if this change does just that. 
</blockquote></details>

I meant, "Is is not..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113)*

**Comment by johlju** [comment]
Reviewed 1 of 3 files at r3, 10 of 10 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113#-:-L0yGXDXB3e-EHidHQJU:bnfp4nl)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CHANGELOG.md, line 3 at r6](https://reviewable.io:443/reviews/powershell/xfailovercluster/113#-L0yH3DE7CZBCFs_ZDAL:-L0yH3DE7CZBCFs_ZDAM:b-de5hay) ([raw file](https://github.com/powershell/xfailovercluster/blob/73d41149d7352302a134776e55b3a0262da6400b/CHANGELOG.md#L3)):*
> ```Markdown
> # Change log for xFailOverCluster
> 
> ## Unreleased
> ```

Need to add an entry for the issue #28 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113)*

**Comment by johlju** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 3 at r6](https://reviewable.io:443/reviews/powershell/xfailovercluster/113#-L0yH3DE7CZBCFs_ZDAL:-L0yH_CFreOZW12KoDuK:bb6un1j) ([raw file](https://github.com/powershell/xfailovercluster/blob/73d41149d7352302a134776e55b3a0262da6400b/CHANGELOG.md#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Need to add an entry for the issue #28 
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/113#-:-L0yHgkza0CEV0MbtlPk:bnfp4nl)*

**Comment by johlju** [comment]
@wasabii Now I merged this one. Thanks for your work on this one! Sorry it took so long getting this thru.

**Comment by wasabii** [comment]
Oh, cool. I'm sorry I completely vanished on you. Got pulled off into other things, and didn't have the time required to get back into it as needed. Also, I don't know crap about PowerShell testing, apparently.

**Comment by johlju** [comment]
No worries. I had a lot of work over at SqlServerDsc and a lot of work on the day job as well, so haven't had much time. You should look into Pester when you have time, it's a good knowledge to have. But here to help with that, just glad you started getting the code changes needed. 😄 
Hope I will see you back here.

**Pull request merged**
