### PR TITLE
xClusterNetwork: Refactor unit test

### LINKED ISSUE #57: xClusterNetwork: Missing an example for this resource
We should add an example for the resource xClusterNetwork.

### LINKED ISSUE #75: xClusterNetwork: Unit tests does not use the correct template and folder structure is wrong
**Details of the scenario you tried and the problem that is occurring:**
Unit tests does not use the correct template and folder structure is wrong

I suggest change so the correct template is used for the unit tests, and that the correct folder structure is used.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xClusterNetwork
  - Refactored the unit test for this resource to use stubs and increase coverage
    (issue #75).
  - Changed the code to be more aligned with the style guideline.
  - Updated resource and parameter description in README.md and schema.mof.
  - Added example (issue #57)
    - 1-ChangeClusterNetwork.ps1
  - Added links to examples from README.md.

**This Pull Request (PR) fixes the following issues:**
Fixes #75 
Fixes #57 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/93)

### CODE REVIEW

**Comment by johlju** [comment]
Closing this and reopen to kick of the AppVeyor test again.

**Comment by johlju** [comment]
@bgelens This one is ready for review whenever you got time.

**Comment by bgelens** [comment]
I think you missed some stuff you normally do :smile:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 99 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoReOL6WqOJVVGsdSkk:-KoReOL6WqOJVVGsdSkl:b-g3yije) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/README.md#L99)):*
> ```Markdown
> ### xClusterNetwork
> 
> Configures as cluster network in a failover cluster.
> ```

configures cluster networks?

---

*[README.md, line 105 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRehi2sBt2-kmkT70Y:-KoRehi2sBt2-kmkT70Z:b-t01zor) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/README.md#L105)):*
> ```Markdown
> 
> #### Role parameter
> ```

I would move this to go below the Parameters

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRewqlu4SOa2u2QZu3:-KoRewqlu4SOa2u2QZu4:bx75ha2) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L14)):*
> ```PowerShell
> {
>     [CmdletBinding()]
>     [OutputType([Hashtable])]
> ```

I believe you normally use the ```[System.Collections.Hashtable]``` here. I don't mind it being like this though ;)

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 90 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRfQ05HC8adOfFggWK:-KoRfQ05HC8adOfFggWL:b-9vigi) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L90)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet('0','1','3')]
> ```

Add space between comma and next value

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 171 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRfkiULUy4xrEH6t2U:-KoRfkiULUy4xrEH6t2V:b-2b57n6) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L171)):*
> ```PowerShell
> {
>     [CmdletBinding()]
>     [OutputType([Boolean])]
> ```

Again, I think you normally make this ```[System.Boolean]```

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 199 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRfzjwqERq7NO-5iHd:-KoRfzjwqERq7NO-5iHe:buatq8c) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L199)):*
> ```PowerShell
> 
>     return (
>         (($Name -eq $getTargetResourceResult.Name) -or (-not $PSBoundParameters.ContainsKey('Name'))) -and
> ```

Not a fan of how this is done...  Marked satisfied as it's not blocking but wanted to make clear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-:-KoRgWviCZ_Exe5Jfelw:b-768o7w)*

**Comment by johlju** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 99 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoReOL6WqOJVVGsdSkk:-KoRm6e1drvp0iuDkhRK:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/README.md#L99)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

configures cluster networks?
</blockquote></details>

Done.

---

*[README.md, line 105 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRehi2sBt2-kmkT70Y:-KoRm7INN1iem85rA0mT:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/README.md#L105)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

I would move this to go below the Parameters
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRewqlu4SOa2u2QZu3:-KoRm8Yts1rul__g5qEf:b-8mi2oe) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L14)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

I believe you normally use the ```[System.Collections.Hashtable]``` here. I don't mind it being like this though ;)
</blockquote></details>

Done. Yes missed that one. 

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 90 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRfQ05HC8adOfFggWK:-KoRmACnH9MHhsIvhgt2:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L90)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Add space between comma and next value
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 171 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRfkiULUy4xrEH6t2U:-KoRmAt-pPZogQxx6dBf:bxatj1p) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L171)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Again, I think you normally make this ```[System.Boolean]```
</blockquote></details>

Done. Missed that one too. ;)

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1, line 199 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoRfzjwqERq7NO-5iHd:-KoRmDKx-UXsHYuAriAZ:b-m7yt6y) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1#L199)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Not a fan of how this is done...  Marked satisfied as it's not blocking but wanted to make clear
</blockquote></details>

Done. Is this better? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/93)*

**Comment by bgelens** [comment]
that logic in test is way easier to read now! :lgtm: with exception of that one sentence.

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 99 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoReOL6WqOJVVGsdSkk:-KoRopvdF0U_qbI5hRGu:b-admnds) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/README.md#L99)):*
> Configures as cluster networks in a failover cluster.
The sentence doesn't ring with me.. Configures as .. should that be Configures a cluster network or ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-:-KoRpEZU2ZYcNjJG5XJt:bs9oxwd)*

**Comment by johlju** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 99 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-KoReOL6WqOJVVGsdSkk:-KoRsCODHPAe4Gv764Mn:b-5g0dxq) ([raw file](https://github.com/powershell/xfailovercluster/blob/ddb68993347320d2a43525fe7f15d3b66952b35d/README.md#L99)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

> Configures as cluster networks in a failover cluster.
The sentence doesn't ring with me.. Configures as .. should that be Configures a cluster network or ??
</blockquote></details>

Done. My bad. Yes it should have been. Thank you for proof reading! :smile: 
My spell checker, checks for misspelled words, not grammar ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/93)*

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/93#-:-KoRtmtLD_l7wtIoIXAV:bnfp4nl)*

**Pull request merged**
