### PR TITLE
xWaitForCluster: Added unit test

### LINKED ISSUE #54: xWaitForCluster: Script Analyzer warnings that need to be fixed
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xWaitForCluster.psm1 (Line 48): File 'MSFT_xWaitForCluster.psm1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
MSFT_xWaitForCluster.psm1 (Line 99): File 'MSFT_xWaitForCluster.psm1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
MSFT_xWaitForCluster.psm1 (Line 49): $null should be on the left side of equality comparisons.
MSFT_xWaitForCluster.psm1 (Line 49): $null should be on the left side of equality comparisons.
MSFT_xWaitForCluster.psm1 (Line 57): $null should be on the left side of equality comparisons.
MSFT_xWaitForCluster.psm1 (Line 100): $null should be on the left side of equality comparisons.
MSFT_xWaitForCluster.psm1 (Line 100): $null should be on the left side of equality comparisons.
MSFT_xWaitForCluster.psm1 (Line 107): $null should be on the left side of equality comparisons.

### LINKED ISSUE #78: xWaitForCluster: Unit tests does not use the correct template and folder structure is wrong
**Details of the scenario you tried and the problem that is occurring:**
Unit tests does not use the correct template and folder structure is wrong

I suggest change so the correct template is used for the unit tests, and that the correct folder structure is used.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### LINKED ISSUE #107: xWaitForCluster: If domain name cannot be evaluated by Test-TargetResource it will return and array containing two $false
**Details of the scenario you tried and the problem that is occurring:**
If domain name cannot be evaluated by Test-TargetResource it will return and array containing two $false.

This is because Test-TargetResource does not honor the return value and does not chnage code path.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xWaitForCluster
  - Refactored the unit test for this resource to use stubs and increase coverage
    (issue #78).
  - Now the Test-TargetResource correctly returns false if the domain namn cannot
    be evaluated  (issue #107).
  - Changed the code to be more aligned with the style guideline.
  - Updated parameter description in the schema.mof.
  - Resolved Script Analyzer warnings (issue #54).

**This Pull Request (PR) fixes the following issues:**
Fixes #78 
Fixes #107 
Fixes #54 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/108)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens And finally the last unit test. Whenever you have to time to review this one.

**Comment by johlju** [comment]
@PlagueHO do you mind to review this one if you have a chance?

**Comment by PlagueHO** [comment]
@johlju - will get onto this tonight after work! A pleasure to help!

**Comment by PlagueHO** [comment]
@Johlju - looking pretty good - just some really minor nitpicks.

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[CHANGELOG.md, line 25 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2LGpoWRVmIgWx_J2:-Kpb2LGpoWRVmIgWx_J3:bi0xv9p) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/CHANGELOG.md#L25)):*
> ```Markdown
>   - Refactored the unit test for this resource to use stubs and increase coverage
>     ([issue #78](https://github.com/PowerShell/xFailOverCluster/issues/78)).
>   - Now the Test-TargetResource correctly returns false if the domain namn cannot
> ```

spelling error here: namn => name

---

*[DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2xXgYSbtJ7X6cBzJ:-Kpb2xXgYSbtJ7X6cBzK:b-3m3j4j) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1#L34)):*
> ```PowerShell
>     )
> 
>     @{
> ```

Not required, but I think it is better to use add a `return` as it makes it clearer.

---

*[DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1, line 173 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb3abZeLm79y4gtMuk:-Kpb3abZeLm79y4gtMul:b-3m3j4j) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1#L173)):*
> ```PowerShell
>     }
> 
>     $testTargetResourceReturnValue
> ```

Not required, but I think it is better to use add a `return` as it makes it clearer.

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb43ZyCEhysAC3Yl8G:-Kpb43Zzgk9FPTvdPAjm:bxx462f) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L96)):*
> ```PowerShell
>                     Mock -CommandName Get-CimInstance -MockWith $mockGetCimInstance -ParameterFilter $mockCimInstance_ParameterFilter -Verifiable
> 
>                     { Set-TargetResource @mockDefaultParameters } | Should -Throw ('Failover cluster {0} not found after {1} attempts with {2} sec interval' -f $mockClusterName, ($mockRetryCount-1), $mockRetryIntervalSec)
> ```

Not something you have to change, but why include the `-`? `Should Be` and `Should BeOfType` are used earlier, but `Should -Throw` and `Should -Not -Throw` format are used. Just a minor consistency thing.

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 108 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb5NwjG6pHe2ATKmm4:-Kpb5NwkXFcg1Y_HgxFH:b-rr9d80) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L108)):*
> ```PowerShell
>                     Context 'When Get-Cluster throws an error' {
>                         BeforeEach {
>                             # This is used for the evaluation of that cluster do not exist.
> ```

Nitpic: `# This is used for the evaluation of a cluster that does not exist.`

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 161 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb4ftTh0u_T3iIbvC1:-Kpb4ftTh0u_T3iIbvC2:b-83pq6e) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L161)):*
> ```PowerShell
>                     Context 'When Get-Cluster throws an error' {
>                         BeforeEach {
>                             # This is used for the evaluation of that cluster do not exist.
> ```

Nitpic: `# This is used for the evaluation of a cluster that does not exist.`

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 193 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb4uN15ZSH7-zjxgOd:-Kpb4uN15ZSH7-zjxgOe:b-ewrjkg) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L193)):*
> ```PowerShell
> 
>                         Assert-VerifiableMocks
>                     }                }
> ```

`}` should be on the next line I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-:-Kpb5STELnmo_ob-L-g5:b7vynne)*

**Comment by johlju** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[CHANGELOG.md, line 25 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2LGpoWRVmIgWx_J2:-KpfDm6qHYeghMWxUic0:bqcbozd) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/CHANGELOG.md#L25)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

spelling error here: namn => name
</blockquote></details>

Done. Thanks! That was the Swedish word for name ;)

---

*[DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2xXgYSbtJ7X6cBzJ:-KpfDw0McPOAKN6c4Ira:ba1zk4i) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1#L34)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not required, but I think it is better to use add a `return` as it makes it clearer.
</blockquote></details>

I tend to agree. I normally do that. But @bgelens like us to not use it unless it it is used to exit a code path. So all other resource are not using 'return' for these.
So I rather keep this as-is as is to be consequent.
If we get a guideline to use return for these, then we change them back. :) I saw Katie asked to get return on these as well in a PR in another repo.

---

*[DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1, line 173 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb3abZeLm79y4gtMuk:-KpfDxDg3cn_ko7b6J8R:b-cxfbnl) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1#L173)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not required, but I think it is better to use add a `return` as it makes it clearer.
</blockquote></details>

Same as previous comment.

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb43ZyCEhysAC3Yl8G:-KpfE1Wq4bslAJqOBt5w:b-ltuzkv) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L96)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not something you have to change, but why include the `-`? `Should Be` and `Should BeOfType` are used earlier, but `Should -Throw` and `Should -Not -Throw` format are used. Just a minor consistency thing.
</blockquote></details>

Done. That's me trying to use the new style of Pester 4.x outside of these repos, and it snuck in.
Fixed this an all others in the repo. 

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 108 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb5NwjG6pHe2ATKmm4:-KpfEH284J9KRAcIXV3Y:bkmmgr2) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L108)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpic: `# This is used for the evaluation of a cluster that does not exist.`
</blockquote></details>

Done. Thanks for proof reading! :smile: 

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 161 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb4ftTh0u_T3iIbvC1:-KpfEKfSX6FWOip1Iulg:bkmmgr2) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L161)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpic: `# This is used for the evaluation of a cluster that does not exist.`
</blockquote></details>

Done. Thanks for proof reading! :smile: 

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 193 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb4uN15ZSH7-zjxgOd:-KpfELrTphXKLBaAJcny:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L193)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

`}` should be on the next line I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/108)*

**Comment by PlagueHO** [comment]
All looking good!
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 25 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2LGpoWRVmIgWx_J2:-Kpg6FT6LrQIX3Q4vIcI:bni0xbo) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/CHANGELOG.md#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Thanks! That was the Swedish word for name ;)
</blockquote></details>

Oh right! I wish I was multilingual! :grin: (listening to lots of Scandinavian extreme metal doesn't give me a good understanding of Swedish).

---

*[DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2xXgYSbtJ7X6cBzJ:-Kpg6omW5Hmoo6CYT0Mk:brdromx) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1#L34)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I tend to agree. I normally do that. But @bgelens like us to not use it unless it it is used to exit a code path. So all other resource are not using 'return' for these.
So I rather keep this as-is as is to be consequent.
If we get a guideline to use return for these, then we change them back. :) I saw Katie asked to get return on these as well in a PR in another repo.
</blockquote></details>

All good! There is a good discussion thread on this over at the PoSHCode PowerShellPracticeAndStyle repo - recommended reading on this topic: https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/46#issuecomment-236727676

It generally agrees with what @bgelens is saying, but I think the difference is interpretation of whether or not the last line of the function is "ending execution". I guess it depends on your coding background - I've come from a C/C++ background and so having a return feels more explicit and clear. But that is just me.

Anyway, not and issue here.

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb43ZyCEhysAC3Yl8G:-Kpg8AzcLOqAGvENib75:b-46jtfp) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. That's me trying to use the new style of Pester 4.x outside of these repos, and it snuck in.
Fixed this an all others in the repo. 
</blockquote></details>

Oh! I hadn't seen that style... I didn't realize. I better look into it :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-:-Kpg8Px78RkLg3oEAwLS:bcnbg8j)*

**Comment by johlju** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[CHANGELOG.md, line 25 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2LGpoWRVmIgWx_J2:-KpizcTuSDLD-oek-Hqj:bk83i1i) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/CHANGELOG.md#L25)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Oh right! I wish I was multilingual! :grin: (listening to lots of Scandinavian extreme metal doesn't give me a good understanding of Swedish).
</blockquote></details>

No wonder, since Scandinavian metal music is in English, Swedish, Norwegian and Danish and probably Sami.  :wink:  Listen to metal band Lillasyster if you haven't, they sing in Swedish. They also has made the best cover (IMHO) of Umbrella (only English song). :smile: 

---

*[DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb2xXgYSbtJ7X6cBzJ:-KpizTMSBRtengTxSLmI:bnnt8p) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1#L34)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

All good! There is a good discussion thread on this over at the PoSHCode PowerShellPracticeAndStyle repo - recommended reading on this topic: https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/46#issuecomment-236727676

It generally agrees with what @bgelens is saying, but I think the difference is interpretation of whether or not the last line of the function is "ending execution". I guess it depends on your coding background - I've come from a C/C++ background and so having a return feels more explicit and clear. But that is just me.

Anyway, not and issue here.
</blockquote></details>

I come from C/C++/C# as well, and I really like ending with `return`. :smile: 

---

*[Tests/Unit/MSFT_xWaitForCluster.Tests.ps1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/108#-Kpb43ZyCEhysAC3Yl8G:-Kpj0hJowErKrhC9jCtE:bziioy2) ([raw file](https://github.com/powershell/xfailovercluster/blob/aa1b3e7464de9143c3e2c2ff88657e7e0efa7089/Tests/Unit/MSFT_xWaitForCluster.Tests.ps1#L96)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Oh! I hadn't seen that style... I didn't realize. I better look into it :grin:
</blockquote></details>

I tried to find a link top a discussion I saw around it over at Pester repo. But didn't find it. They changed it to use `-Be` etc. to be able to introduce more parameters if I understood it correctly, because having them set by position was somewhat limiting. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/108)*

**Pull request merged**
