### PR TITLE
xCluster: Make parameter DomainAdministratorCredential non-mandatory

### PR DESCRIPTION
**Pull request by Woogyz**
**Pull Request (PR) description**
Hello -

I ran into an issue when utilizing this resource where I didn't want to provide a DA credential. In my environment, we utilize machine identities to ACL most of our resources so we can avoid using passwords in 99.9% of situations. Unfortunately, this resource doesn't support this.

I got around this by doing the following:

- Changed the "DomainAdministratorCredential" property in the schema to "write" (was required).
- Changed the "DomainAdministratorCredential" parameter in the resource to "Mandatory = $false".
- Wrapped the Set-ImpersonateAs function in an if statement to check for the "DomainAdministratorCredential" key exists in $PSBoundParameters.

If you need more documentation, explanation please let me know.

**This Pull Request (PR) fixes the following issues:**
None

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/163)

### CODE REVIEW

**Comment by johlju** [comment]
First thanks for the contribution! Is it  possible for you to resolve the review comment on top of these?

* Can you please add an issue describing your issue and proposed solution?
* Can you add an entry to the Unreleased section of the CHANGELOG.md?
* Can you add an example on how to write a configuration in your scenario?
* Can you update the xCluster parameter description in the README.md?
* Can you please rebase so that the units tests will pass (just merged a fix). Please use `git rebase` (and not `git merge` or `git pull`) to keep commit history.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 32 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/163#-L0yKYpnKbCsh8AaGG_n:-L0yKYpnKbCsh8AaGG_o:b-akizco) ([raw file](https://github.com/powershell/xfailovercluster/blob/5393303e1da08179a840b723f3fb5b36df7ec879/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L32)):*
> [Parameter(Mandatory = $false)]

As per style guideline this should be changed to `[Parameter()]`. Throughout.

---

*[DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 48 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/163#-L0yL1553uS9Lr1o4y0w:-L0yL1553uS9Lr1o4y0x:b-ewrxgs) ([raw file](https://github.com/powershell/xfailovercluster/blob/5393303e1da08179a840b723f3fb5b36df7ec879/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L48)):*
> $PSBoundParameters.Keys -contains "$DomainAdministratorCredential"

Can we change this to `$PSBoundParameters.ContainsKey('DomainAdministratorCredential')`? If so, throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/163#-:-L0yJ8eM8MxGrxpuXAAc:b24ha20)*

**Comment by Woogyz** [comment]
Sorry, still new to GitHub (first time contributing back).

Can you please add an issue describing your issue and proposed solution?
- Done

Can you add an entry to the Unreleased section of the CHANGELOG.md?
- Done

Can you add an example on how to write a configuration in your scenario?
- Done, added a new example configuration.

Can you update the xCluster parameter description in the README.md?
- Done

Can you please rebase so that the units tests will pass (just merged a fix). Please use git rebase (and not git merge or git pull) to keep commit history.
- Not sure how to do this, I don't have git on my local machine for one, and for two (and I hope this doesn't make it more complicated), I did the pull request for the master branch. The dev branch was really messed up (I think you fixed the issues), so I wasn't using it.

Thanks!

**Comment by johlju** [comment]
@Woogyz I changed the base branch to the dev banch. Only releases update the master branch. But doing so there I a lot of conflicts. So to solve this I think the easiest is to create a new working-branch an PR in that instead. We need to use a little git-fu.

I will assume you don't have cloned the repo. If you did, then you can skip those steps. You must run these git commands on your local repo (you need to do this on your machine).
I ran thru these steps on my end, so it should work. It can be a bit tricky to resolve the merge conflicts; i tried to add comments below, but read up here as well if you like; https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

```
mkdir c:\temp\source
cd c:\temp\source
git clone https://github.com/Woogyz/xFailOverCluster
cd .\xFailOverCluster\
git remote add PowerShell https://github.com/PowerShell/xFailOverCluster
git checkout master
git checkout -b workingbranch1
git fetch PowerShell dev
git rebase PowerShell/dev
# At this point there will be merge conflicts - open MSFT_xCluster.psm1 in any edit to edit the code, preferably use  Visual Studio Code. Look for '<<<<<<< HEAD'. Manually edit the code so it is correct with your changes.
git add * # Or stage the file(s) in Visual Studio Code
git rebase --continue
# At this point there will be merge conflicts - open MSFT_xCluster.schema.mof. Look for '<<<<<<< HEAD'.  Repeat as previously.
git add * # Or stage the file(s) in Visual Studio Code
git rebase --continue
# At this point there will be merge conflicts - open CHANGELOG.md and README.md. Look for '<<<<<<< HEAD'. There a BIG conflicts in both of these, so easiest might just be to accept current change (see Visual Studio Code it helps here, a lot!) and after that just remake your changes.
git add * # Or stage the file(s) in Visual Studio Code
git rebase --continue
git push origin workingbranch1 # Use --force here it it complains, but it shouldn't sinve the branch does not exist in your fork.
```

Now you have a new branch in your fork that you can PR in to xFailOverCluster.

**Comment by johlju** [comment]
@Woogyz Did the steps I provided work for you?

**Comment by Woogyz** [comment]
Will try them out today, thanks for the detailed steps!!

**Comment by johlju** [comment]
No problem, happy to help. Heads up, I just merged a new PR that changes xCluster so there might be more conflicts to resolve than I listed in the steps, but same procedure for those as well. 
But since you branching (`workingbranch1`), you can try it several times, just create a new branch each time (for example `git checkout -b workingbranch2`).

**Comment by johlju** [comment]
@Woogyz how did it go? Let me know if you need any help.

**Comment by johlju** [comment]
@Woogyz Do you have time to work on this PR?

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by johlju** [comment]
Closing this PR due to inactivity. If there are someone who wants to work on this issue or PR please open a new PR.

**Pull request closed without merging**
