### PR TITLE
Fixed wrong variable name

### PR DESCRIPTION
**Pull request by gigi81**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/17)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 123 \[r1\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/17#-KIz6imfhibSKjyjWAAh:-KIz6imfhibSKjyjWAAi:1007013546) ([raw file](https://github.com/powershell/xfailovercluster/blob/7e7918ea1036b6ab4e046b67b863a6a9ab35f447/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L123)):*
> ```PowerShell
>     return (
>         (($Ensure -eq $CurrentDisk.Ensure) -or (-not $PSBoundParameters.ContainsKey('Ensure'))) -and
>         (($Ensure -eq $CurrentDisk.Label) -or (-not $PSBoundParameters.ContainsKey('Label')))
> ```


It is required that you provide adequate test coverage for the code you change according to the [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Existing tests exist it should be easy enough to add a test for this condition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/17)*

**Comment by gigi81** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1, line 123 \[r1\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/17#-KIz6imfhibSKjyjWAAh:-KJ-tooHvmL1HcoLcHIv:445410846) ([raw file](https://github.com/powershell/xfailovercluster/blob/7e7918ea1036b6ab4e046b67b863a6a9ab35f447/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1#L123)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> 
> It is required that you provide adequate test coverage for the code you change according to the [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.
> 
> Existing tests exist it should be easy enough to add a test for this condition.
</details>
Added 7 tests as requested and found some more issues and fixed them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/17)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/17)*

**Comment by TravisEz13** [comment]
Thanks for your contribution!

<details><summary><i>Previously, msftclas (Microsoft Contribution License Agreements) wrote…</i></summary>
> Hi __@gigi81__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
> 
>     <span>
> 
>         This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
> 
>     </span>
> 
> 
> 
> TTYL, MSBOT;
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/17#-:-KJ3NCDJd6dojkMqFSXk:-505258547)*

**Pull request merged**
