### PR TITLE
xClusterPreferredOwner: Refactor unit test

### LINKED ISSUE #52: xClusterPreferredOwner: Missing an example for this resource
We should add an example for the resource xClusterPreferredOwner.

### LINKED ISSUE #76: xClusterPreferredOwner: Unit tests does not use the correct template and folder structure is wrong
**Details of the scenario you tried and the problem that is occurring:**
Unit tests does not use the correct template and folder structure is wrong

I suggest change so the correct template is used for the unit tests, and that the correct folder structure is used.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xClusterPreferredOwner
  - Refactored the unit test for this resource to use stubs and increase coverage
    (issue #76).
  - Changed the code to be more aligned with the style guideline.
  - Added examples (issue #52)
    - 1-AddPreferredOwner.ps1
    - 2-RemovePreferredOwner.ps1
  - Added links to examples from README.md.

**This Pull Request (PR) fixes the following issues:**
Fixes #76
Fixes #52 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/98)

### CODE REVIEW

**Comment by johlju** [comment]
Closing this and reopen to kick off the AppVeyor test again.

**Comment by bgelens** [comment]
Small things. Looking good!

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 81 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOHA3XJnw9XHYsV5Ji:-KoOHA3XJnw9XHYsV5Jj:b-rao5lr) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/CHANGELOG.md#L81)):*
> ```Markdown
>     should remove a disk (issue #90).
>   - Changed the code to be more aligned with the style guideline.
>   - Added examples (issue ¤46)
> ```

Unicode char?

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 64 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOMu9L1FzGai7M82B8:-KoOMu9L1FzGai7M82B9:b-hoqbdp) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L64)):*
> ```PowerShell
>                 Write-Verbose -Message "Retrieving Owner information for Cluster Resource $resource"
>                 (((Get-ClusterResource -Cluster $ClusterName) | Where-Object -FilterScript {
>                     $_.Name -like $resource
> ```

why like? are there wildcards allowed for $ClusterResources?

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 163 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOPCfZoFifczIwiM7y:-KoOPCfZoFifczIwiM7z:bvvwwi0) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L163)):*
> ```PowerShell
>         } | Get-ClusterOwnerNode).OwnerNodes).Name | Sort-Object -Unique
> 
>         $newOwners = @(
> ```

Personally I would think a resource like this handles only one state. So **ensure** doesn't make sense to me. Instead I would think the resource would govern the owners specified in the configuration and would purge anything else instead of being additive. I'll mark this as satisfied as it is not blocking but just wanted to give my opinion :)

---

*[Examples/Resources/xClusterPreferredOwner/2-RemovePreferredOwner.ps1, line 31 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOPyBNDjvbhzrovy_S:-KoOPyBNDjvbhzrovy_T:bhv3wtn) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/Examples/Resources/xClusterPreferredOwner/2-RemovePreferredOwner.ps1#L31)):*
> ```PowerShell
>         xClusterPreferredOwner 'RemoveOwnersForClusterGroup2'
>         {
>             Ensure = 'Absent'
> ```

This is what I was talking about... The resource is handling desired state a an imperative operation. So to fix a situation, first I have to remove owners, then push another config that would be consistent with my desired state... see what I mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-:-KoORM14DnvGwhCI9AB1:blrr7n6)*

**Comment by johlju** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 81 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOHA3XJnw9XHYsV5Ji:-KoRg6NyaID5vNk9JFuH:b-c4rb7t) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/CHANGELOG.md#L81)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Unicode char?
</blockquote></details>

Done. Hit the wrong key ;)

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 64 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOMu9L1FzGai7M82B8:-KoRgCkUxjp7OgK9PEMz:b-9ul66l) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L64)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

why like? are there wildcards allowed for $ClusterResources?
</blockquote></details>

Done. Submitted issue #101 (BREAKING CHANGE: xClusterPreferredOwner: Resource allows wildcards for ClusterGroup and ClusterResources) 

---

*[DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1, line 163 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOPCfZoFifczIwiM7y:-KoRgWeofUy80-gN5DrE:bmwb00p) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1#L163)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Personally I would think a resource like this handles only one state. So **ensure** doesn't make sense to me. Instead I would think the resource would govern the owners specified in the configuration and would purge anything else instead of being additive. I'll mark this as satisfied as it is not blocking but just wanted to give my opinion :)
</blockquote></details>

Done. Submitted issue #102 (xClusterPreferredOwner: Is the behavior of parameter Ensure correct?) to discuss this.

---

*[Examples/Resources/xClusterPreferredOwner/2-RemovePreferredOwner.ps1, line 31 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-KoOPyBNDjvbhzrovy_S:-KoRgilBpkOOsp1d0eF5:bmwb00p) ([raw file](https://github.com/powershell/xfailovercluster/blob/f740ef12464d501d2076e56bd27b5e116afd4c1f/Examples/Resources/xClusterPreferredOwner/2-RemovePreferredOwner.ps1#L31)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

This is what I was talking about... The resource is handling desired state a an imperative operation. So to fix a situation, first I have to remove owners, then push another config that would be consistent with my desired state... see what I mean?
</blockquote></details>

Done. Submitted issue #102 (xClusterPreferredOwner: Is the behavior of parameter Ensure correct?) to discuss this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/98)*

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/98#-:-KoRhfiZuFebqnpCgdVq:bnfp4nl)*

**Pull request merged**
