### PR TITLE
xClusterQuorum: Fixed the filesharewitness checks

### LINKED ISSUE #35: xClusterQuorum: Test-TargetResource fails on Windows Server 2016 using NodeAndFileShareMajority
Using the following configuration the quorum is set correctly. But in subsequently calls to Test-TargetResource, the call fails with error 'Unknown quorum resource: File Share Witness'. 

```
xClusterQuorum ClusterConfigureQuorum
{
    IsSingleInstance = 'Yes'
    Type = 'NodeAndFileShareMajority'
    Resource = "\\fileserver.company.local\clusterwitness$" 
    PsDscRunAsCredential = $installCredential 
}
```

This is because when evaluating it uses the following code

``` 
elseif ($ClusterQuorum.QuorumResource.ResourceType.DisplayName -eq 'File Share Witness')
{
    $ClusterQuorumType = 'NodeAndFileShareMajority'
}
```

But the property `DisplayName` is actually set to 'File Share Quorum Witness'. The property `Name` and `ResourceType` is set to 'File Share Witness'.

```
PS > $ClusterQuorum.QuorumResource

Name               State  OwnerGroup    ResourceType      
----               -----  ----------    ------------      
File Share Witness Online Cluster Group File Share Witness

PS > $ClusterQuorum.QuorumResource.ResourceType

Name               DisplayName              
----               -----------              
File Share Witness File Share Quorum Witness

PS > $ClusterQuorum.QuorumResource.ResourceType.DisplayName
File Share Quorum Witness
````

So either we change so that we evaluate the property `Name`, or we change evaluation to look for the correct DisplayName. If I look at the properties in the GUI, then the Type is set to 'File Share Quorum Witness'. So I guess that correlates to the DisplayName property, and Name can be changed by the user. So I guess we need to change to the correct display name string value.

image

### PR DESCRIPTION
**Pull request by Blankf**
**Pull Request (PR) description**
- Changes to xClusterQuorum
  - When using NodeAndFileShareMajority on Windows Server 2016 any subsequent run
    failed when Test-TargetResource validated the configuration.

**This Pull Request (PR) fixes the following issues:**
Fixes #35

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible

Previous PR-> https://github.com/PowerShell/xFailOverCluster/pull/141

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/144)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for sending is this PR! Really appreciate this! :smile: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 3 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-KtWpESujD9NFLrzl2RD:-KtWpESujD9NFLrzl2RE:b-rjzcuv) ([raw file](https://github.com/powershell/xfailovercluster/blob/d3288a1fc91295cf6833dacbdbdccd2e9e1e9296/CHANGELOG.md#L3)):*
> ```Markdown
> # Change log for xFailOverCluster
> 
> ## Unreleased
> ```

Please fix lint errors in this README.md (tests are failing)

https://ci.appveyor.com/project/PowerShell/xfailovercluster/build/1.6.273.0#L374

---

*[CHANGELOG.md, line 5 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-KtWpUij_wNLDX5wUgZq:-KtWpUij_wNLDX5wUgZr:bbla3wh) ([raw file](https://github.com/powershell/xfailovercluster/blob/d3288a1fc91295cf6833dacbdbdccd2e9e1e9296/CHANGELOG.md#L5)):*
> server 2016 test failed on nodeandfilesharemajority if you used filesharemajority

Please make this more descriptive. What do you think of "When using NodeAndFileShareMajority on Windows Server 2016 any subsequent run failed when Test-TargetResource validated the configuration."?

---

*[README.md, line 183 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-KtWqzu90r5U6E2n7KkT:-KtWqzu90r5U6E2n7KkU:b-5g8og5) ([raw file](https://github.com/powershell/xfailovercluster/blob/d3288a1fc91295cf6833dacbdbdccd2e9e1e9296/README.md#L183)):*
> ```Markdown
>   NodeMajority.
> 
> >Note: if you want to use FileShareWitness, use NodeAndFileShareMajority.
> ```

Please add the other two as well

NodeMajority = NoWitness
NodeAndDiskMajority = DiskWitness

---

*[README.md, line 183 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-KtWrDwPM05tNxT1NHkz:-KtWrDwPM05tNxT1NHl-:bk9ck3k) ([raw file](https://github.com/powershell/xfailovercluster/blob/d3288a1fc91295cf6833dacbdbdccd2e9e1e9296/README.md#L183)):*
> use NodeAndFileShareMajority

Maybe "..., use the option NodeAndFileShareMajority."?

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 42 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-KtWra_d2qVR02BwdfQx:-KtWra_d2qVR02BwdfQy:bs3xjzd) ([raw file](https://github.com/powershell/xfailovercluster/blob/d3288a1fc91295cf6833dacbdbdccd2e9e1e9296/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L42)):*
> ```PowerShell
>                 $clusterQuorumType = 'NodeAndDiskMajority'
>             }
>             elseif ($getClusterQuorumResult.QuorumResource.ResourceType.DisplayName -eq 'File Share Witness' -or $getClusterQuorumResult.QuorumResource.ResourceType.DisplayName -eq 'File Share Quorum Witness')
> ```

Could you please write (add) a unit test for this change? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-:-KtWrji1DRPSWmHNz7TG:b-nc4c74)*

**Comment by Blankf** [comment]
Hi Johlju,

changed the readme and changelog, need to take a look later at the tests.

**Comment by johlju** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 185 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-KtauWtIyDwiFz7NZSo-:-KtauWtIyDwiFz7NZSo0:b-a4r66m) ([raw file](https://github.com/powershell/xfailovercluster/blob/3f2fe6904a3f2b78ccc4f3edc008c565d4ebc71b/README.md#L185)):*
> ```Markdown
> >Note: if you want to use FileShareWitness, use the option NodeAndFileShareMajority.
> >Note: if you want to use DiskWitness, use the option NodeAndDiskMajority.
> >Note: if you want to use NoWitness, use the option NodeMajority.
> ```

Could you please revise these? If you look at the result [here](https://github.com/Blankf/xFailOverCluster/blob/3f2fe6904a3f2b78ccc4f3edc008c565d4ebc71b/README.md#parameters-for-xclusterquorum) you see that they are concatenated, and 'Note:' is part of the paragraph. Maybe revise these so only one 'Note:' is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/144)*

**Comment by Blankf** [comment]
Hi johlju,

can you help me out with the checks, i have looked at them a couple of times but cant seem to get them fixed.

**Comment by johlju** [comment]
@Blankf Sorry that I haven't answered you for so long! 😞 Shall we try get this one over the finish line now? I can help you with the tests. Maybe you can resolve the review comments? If you don't have time then please check the 'Allow edit from maintainers' to the right here and I will get this one over the finish line,

**Comment by Blankf** [comment]
Hi Johlju,

i would really appriciate if you can finish the PR.
at this moment, i dont have any time to do the fixes.

i've ticked the box "Allow edits from maintainers."

Thank you.

**Comment by johlju** [comment]
@Blankf Sure I will get this over the finish line. Thanks for ticking the box. And thanks for contirbuting, hope I will see you back here again!

**Comment by johlju** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/144)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/144#-:-L21ZivlheAe9ui5yvTD:bnfp4nl)*

**Comment by johlju** [comment]
@Blankf So this one is over the finish line! Thanks for contribution this change, I hope I see you here again! 😄

**Pull request merged**
