### PR TITLE
xClusterNetwork: Fix xClusterNetwork errors for Windows Server 2012

### LINKED ISSUE #191: xClusterNetwork: Fails on WS2012 as the Update method doesn't exist
#### Details of the scenario you tried and the problem that is occurring
I'm renaming cluster network adapters with this. It renames the network adapter but fails with an error.

This is because in 2012 cluster module the Update method did not exist and was not needed, any change to the object would take effect immediately. 

So it works, throws an error, but on the next run passes (because the Test passes and the Set isn't needed again).

It should be fixed though.

#### Verbose logs showing the problem
```
VERBOSE: [SEC1N1]:                            [[xClusterNetwork]RenameClusterNetworkC1Heartbeat] Connecting to cluster
on local computer SEC1N1.
Method invocation failed because [Microsoft.FailoverClusters.PowerShell.ClusterNetwork] does not contain a method
named 'Update'.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : SEC1N1

VERBOSE: [SEC1N1]: LCM:  [ End    Set      ]  [[xClusterNetwork]RenameClusterNetworkC1Heartbeat]  in 0.0780 seconds.
The PowerShell DSC resource '[xClusterNetwork]RenameClusterNetworkC1Heartbeat' with SourceInfo
'C:\Lability\Configurations\WS2012.ps1::288::17::xClusterNetwork' threw one or more non-terminating errors while
running the Set-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : SEC1N1
```

#### Suggested solution to the issue
Simply wrap the 3 Update calls in xClusterNetwork like so:

```
        if ($clusterNetworkResource.psobject.Methods['Update']) {
            $clusterNetworkResource.Update()
        }
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
                xClusterNetwork "RenameClusterNetwork$($cluster.Name)Heartbeat" {
                    Address = $clusterIgnoreNetwork.NetworkID
                    AddressMask = $clusterIgnoreNetwork.SubnetMask
                    Name = $clusterIgnoreNetwork.Name
                    Role = 1 # Heartbeat Only

                    DependsOn = "[xCluster]AddNodeToCluster$($cluster.Name)"
                }
```

#### The operating system the target node is running
Windows Server 2012

#### Version and build of PowerShell the target node is running
WMF 5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by codykonior**
#### Pull Request (PR) description
Wraps calls to the Update method on cluster network options in a test confirming that the method exists. The method doesn't exist on Windows Server 2012 because changing the object automatically updates. Not fixing it results in an error.

Tests have been added which change the mock on 2012 to not have an Update method. Then the tests are compared against 0 calls versus whatever number of calls is there for 2016.

#### This Pull Request (PR) fixes the following issues
- Fixes #191 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/192)

### CODE REVIEW

**Comment by johlju** [comment]
@codykonior Thanks for this! I will review this as soon as I can. I'm away this weekend so if I can't get to it during the weekend, I will get to it next week. 🙂

**Comment by codykonior** [comment]
Style changes and variable rename done.

**Comment by codykonior** [comment]
I remember you saying you were travelling. Gentle reminder that this is ready for review again.

**Comment by johlju** [comment]
@codykonior I have this on my todo - will try to get to it tonight. 🙂

**Comment by codykonior** [comment]
In defense of psobject, it's documented and used in PowerShell Core and other DSC Resources with no indication it's going anywhere.

But I know some people prefer PowerShell conventions to .NET style ones and I could make the change easily so I've done so.

MemberType Method didn't work well because the mocks are a ScriptMethod type. However it appears there's a MemberType property of Methods which covers both so that's what I used.

**Pull request merged**
