### PR TITLE
xClusterNetwork resource

### PR DESCRIPTION
**Pull request by claudiospizzi**
I've added a resource to manage cluster networks

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/10)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Please include a summary of changes in an unreleased version change per the [contribution guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request)

It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

**Comment by TravisEz13** [comment]
If there is no update of the pull request within 7 days, we will close the pull request.  After that, if you have an update, feel free to reopen the pull request or a new pull request.  Please consider closing and re-opening when ready for review.

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.schema.mof, line 7 \[r2\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/10#-KEcF4xAWHlBXEg1WhWI:-KEcF4xAWHlBXEg1WhWJ:-1247230765) ([raw file](https://github.com/powershell/xfailovercluster/blob/37b8d312e7e37a80e469b6bf700ec636fdde4b3f/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.schema.mof#L7)):*
It looks like name should be required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/10)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 16 \[r3\]](https://reviewable.io:443/reviews/powershell/xfailovercluster/10#-KFC8P2wdx5xP-RoC8Do:-KFC8P2wdx5xP-RoC8Dp:1146265129) ([raw file](https://github.com/powershell/xfailovercluster/blob/61c7848fea5dda6887f1f03f8297f5ab7bc90b17/README.md#L16)):*
Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
[Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/10)*

**Comment by claudiospizzi** [comment]
I've merged my changed. I had to add the following command to install the Failover Cluster module to be able to mock these cmdlets:
`Add-WindowsFeature -Name RSAT-Clustering-PowerShell -ErrorAction SilentlyContinue`

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/10)*

**Pull request merged**
