### PR TITLE
xFailOverCluster: Localization support, localized strings in xClusterDisk and some cleanup.

### LINKED ISSUE #84: xClusterDisk: Localization should change to align with HQRM modules
**Details of the scenario you tried and the problem that is occurring:**
Resource should use the same method of localization as HQRM modules (PSDscResource).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xFailOverCluster
  - Added a common resource helper module with helper functions for localization.
    - Added helper functions; Get-LocalizedData, New-InvalidResultException, New-ObjectNotFoundException, InvalidOperationException and InvalidArgumentException.
  - Fixed lint error MD034 and fixed typos in README.md.
- Changes to xClusterDisk
  - Enabled localization for all strings (issue #84).
- Changes to xClusterPreferredOwner
  - Replace an URL which describes more generic the Role setting for xClusterNetwork.

**This Pull Request (PR) fixes the following issues:**
Fixes #84 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/111)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens When you have some time over to review here in xFailOverCluster, could you then please review this one first? I need this merged to be able to do localization for the other resources. 😄

**Comment by johlju** [comment]
@PlagueHO since @bgelens is very busy with the normal day job. Do you have time to review this one? It basically just adds the localization helper functions, and localizes one of the resource (and some minor tweaks). When I get this in I can localize the rest of the resources. 😄

**Comment by PlagueHO** [comment]
Hi @johlju - I definitely will but it will be in about 48 hours. I've taken a short holiday in the mountains in NZ for a bit of snow. Will be back in review zone in  2 days :grin:

**Comment by johlju** [comment]
No worries :) I have also taken 48 hours leave from DSC, but for some summer and nature 😜

**Comment by PlagueHO** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97QPVkz7i8b5rNQYD:-Kp97QPVkz7i8b5rNQYE:b-w6aeww) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L8)):*
> ```Markdown
>   - Added a common resource helper module with helper functions for localization.
>     - Added helper functions; Get-LocalizedData, New-InvalidResultException,
>       New-ObjectNotFoundException, InvalidOperationException and InvalidArgumentException.
> ```

Shouldn't these be:
`New-InvalidOperationException` and `New-InvalidArgumentException`

---

*[CHANGELOG.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97ccOh13QoSCyVu_a:-Kp97ccOh13QoSCyVu_b:b5ajjy4) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L11)):*
> ```Markdown
>   - Fixed lint error MD034 and fixed typos in README.md.
> - Changes to xClusterDisk
>   - Enabled localization for all strings (issue #84).
> ```

Maybe remove # and include link to actual GitHub issue.

---

*[CHANGELOG.md, line 13 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97mqGDKOv3Nm2g4O5:-Kp97mqGDKOv3Nm2g4O6:bi6vz5m) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L13)):*
> ```Markdown
>   - Enabled localization for all strings (issue #84).
> - Changes to xClusterNetwork
>   - Replaced an URL which describes more generic the Role setting for xClusterNetwork.
> ```

This doesn't read quite right. Perhaps something like:
"Replaced the URL with a more generic one which describes the Role setting for xClusterNetwork."

Although, to be honest I'm not sure that is correct either as I didn't quite understand the exact change...

---

*[DSCResources/CommonResourceHelper.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp98bfEU6C-NilkOHRy:-Kp98bfEU6C-NilkOHRz:b-5vo23d) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/DSCResources/CommonResourceHelper.psm1#L60)):*
> ```PowerShell
>         $Message,
> 
>         [ValidateNotNull()]
> ```

Need:
`[Parameter()]`

---

*[DSCResources/CommonResourceHelper.psm1, line 111 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp98iHD7tOxuAcUwSpT:-Kp98iHD7tOxuAcUwSpU:b-5vo23d) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/DSCResources/CommonResourceHelper.psm1#L111)):*
> ```PowerShell
>         $Message,
> 
>         [ValidateNotNull()]
> ```

Need:
`[Parameter()]`

---

*[DSCResources/CommonResourceHelper.psm1, line 162 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp98vq6XFPTk7qZW91o:-Kp98vq6XFPTk7qZW91p:b-5vo23d) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/DSCResources/CommonResourceHelper.psm1#L162)):*
> ```PowerShell
>         $Message,
> 
>         [ValidateNotNull()]
> ```

Need:
`[Parameter()]`

---

*[Tests/Unit/CommonResourceHelper.Tests.ps1, line 123 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp9ABmnM67lwCBRN5b7:-Kp9ABmonuyEMcBvo6ab:b-vt83oh) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/Tests/Unit/CommonResourceHelper.Tests.ps1#L123)):*
> ```PowerShell
>                     $mockErrorRecord = New-Object System.Management.Automation.ErrorRecord $mockException, $null, 'InvalidResult', $null
> 
>                     { New-InvalidResultException -Message $mockErrorMessage -ErrorRecord $mockErrorRecord } | Should Throw 'System.Exception: Mocked error ---> System.Exception: Mocked exception error message'
> ```

I'd suggest that if you're defining the `$mockErrorMessage` and `$mockExceptionErrorMessage` variables and creating the exception with it that you use these in the "Should Throw" - e.g. `Should Throw ('System.Exception: {0} ---> System.Exception: {1}' -f $mockErrorMessage, $mockExceptionErrorMessage) `

Same thing in the next few tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/111)*

**Comment by PlagueHO** [comment]
@johlju - sometimes taking a break is a great idea :grin: Need to recharge every now and then.

**Comment by johlju** [comment]
@PlagueHO thanks for reviewing! Thanks for finding all these! Fixed some in xSQLServer too.

---

Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97QPVkz7i8b5rNQYD:-KpEPJnfYuVWtUBoDTNc:b-q7m29u) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Shouldn't these be:
`New-InvalidOperationException` and `New-InvalidArgumentException`
</blockquote></details>

Done. Yes, it should be. :)

---

*[CHANGELOG.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97ccOh13QoSCyVu_a:-KpEPbdosFj6-XphxC_2:bz81cnt) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Maybe remove # and include link to actual GitHub issue.
</blockquote></details>

Done. I changed all in the change log to be consequent. I kept the # because that is how it looks when you reference issues in comments and such. Do you think it looks better/should be without the #-sign?

---

*[CHANGELOG.md, line 13 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97mqGDKOv3Nm2g4O5:-KpEPsH7_3LnU-XLeIxu:bcr2tci) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This doesn't read quite right. Perhaps something like:
"Replaced the URL with a more generic one which describes the Role setting for xClusterNetwork."

Although, to be honest I'm not sure that is correct either as I didn't quite understand the exact change...
</blockquote></details>

Done. Rephrased, is it better now? :) That was me being blind for my own change. :/

---

*[DSCResources/CommonResourceHelper.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp98bfEU6C-NilkOHRy:-KpEQKXQ-DKYluTRZcT8:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/DSCResources/CommonResourceHelper.psm1#L60)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Need:
`[Parameter()]`
</blockquote></details>

Done.

---

*[DSCResources/CommonResourceHelper.psm1, line 111 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp98iHD7tOxuAcUwSpT:-KpEQL1xqhuLCRBQaTMw:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/DSCResources/CommonResourceHelper.psm1#L111)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Need:
`[Parameter()]`
</blockquote></details>

Done.

---

*[DSCResources/CommonResourceHelper.psm1, line 162 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp98vq6XFPTk7qZW91o:-KpEQLRWHrhtXYKsXtOq:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/DSCResources/CommonResourceHelper.psm1#L162)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Need:
`[Parameter()]`
</blockquote></details>

Done.

---

*[Tests/Unit/CommonResourceHelper.Tests.ps1, line 123 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp9ABmnM67lwCBRN5b7:-KpEQND1XwUtuowHsHGi:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/Tests/Unit/CommonResourceHelper.Tests.ps1#L123)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'd suggest that if you're defining the `$mockErrorMessage` and `$mockExceptionErrorMessage` variables and creating the exception with it that you use these in the "Should Throw" - e.g. `Should Throw ('System.Exception: {0} ---> System.Exception: {1}' -f $mockErrorMessage, $mockExceptionErrorMessage) `

Same thing in the next few tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-:-KpEQQ6yui89pvoWBXp1:bs89wkh)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97ccOh13QoSCyVu_a:-KpH6u5mWsCLKB9xM1ZE:b-t9zyws) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. I changed all in the change log to be consequent. I kept the # because that is how it looks when you reference issues in comments and such. Do you think it looks better/should be without the #-sign?
</blockquote></details>

I'm fine with the sign - it does look better with it in. Let's keep it!

---

*[CHANGELOG.md, line 13 at r2](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-Kp97mqGDKOv3Nm2g4O5:-KpH6cNGXKzjk4L0QPq7:bb35gkf) ([raw file](https://github.com/powershell/xfailovercluster/blob/9d395147c93b942852b81181f05240627a49a53c/CHANGELOG.md#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Rephrased, is it better now? :) That was me being blind for my own change. :/
</blockquote></details>

Yep - much clearer! I understand now :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/111#-:-KpH722qVNS6sNGpbVV1:bnfp4nl)*

**Pull request merged**
