### PR TITLE
xCluster: Enabled localization

### LINKED ISSUE #83: xCluster: Localization should change to align with HQRM modules
**Details of the scenario you tried and the problem that is occurring:**
Resource should use the same method of localization as HQRM modules (PSDscResource).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xFailOverCluster
  - Added common test helper functions to help test the throwing of localized error strings.
    - Get-InvalidArgumentRecord
    - Get-InvalidOperationRecord
    - Get-ObjectNotFoundException
    - Get-InvalidResultException.
- Changes to xCluster
  - Enabled localization for all strings (issue #83).
  - Added tests to improve code coverage.

**This Pull Request (PR) fixes the following issues:**
Fixes #83 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/118)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO do you have time to review this one for me? No hurry.

**Comment by PlagueHO** [comment]
No problem @johlju - will review tomorrow night after work (bed time now!)

Looks like build is failing though..

**Comment by johlju** [comment]
Yes. :/ Tried to improve them. They worked when I ran the tests with `-Tag Helper` but not when all tests ran together...  trying to fix the tests now.

**Comment by johlju** [comment]
Okay, the tests work now, yay! 😄

**Comment by PlagueHO** [comment]
Looks almost perfect. Just two trivial changes.

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 18 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-Kpsno9Ww5CKLndr5waR:-Kpsno9Ww5CKLndr5waS:bhmdgjx) ([raw file](https://github.com/powershell/xfailovercluster/blob/ac17b35d387867458440115d8275a8fc82457779/Tests/TestHelpers/CommonTestHelper.psm1#L18)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

Change to `System.String` To be consistent with other code in the module.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 23 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-Kpsnx-Y6OfRUvaXyWbL:-Kpsnx-Y6OfRUvaXyWbM:bhmdgjx) ([raw file](https://github.com/powershell/xfailovercluster/blob/ac17b35d387867458440115d8275a8fc82457779/Tests/TestHelpers/CommonTestHelper.psm1#L23)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

Change to `System.String` To be consistent with other code in the module.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 63 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-KpsnypwRvK_wR061A0n:-KpsnypwRvK_wR061A0o:bhmdgjx) ([raw file](https://github.com/powershell/xfailovercluster/blob/ac17b35d387867458440115d8275a8fc82457779/Tests/TestHelpers/CommonTestHelper.psm1#L63)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

Change to `System.String` To be consistent with other code in the module.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-:-Kpsp2KGANctTdoZb-h8:bnqwmx8)*

**Comment by johlju** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 18 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-Kpsno9Ww5CKLndr5waR:-KptfjeVB5WOjTnIJD0R:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/ac17b35d387867458440115d8275a8fc82457779/Tests/TestHelpers/CommonTestHelper.psm1#L18)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Change to `System.String` To be consistent with other code in the module.
</blockquote></details>

Done.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 23 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-Kpsnx-Y6OfRUvaXyWbL:-KptfkC32wTHewHbwnSc:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/ac17b35d387867458440115d8275a8fc82457779/Tests/TestHelpers/CommonTestHelper.psm1#L23)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Change to `System.String` To be consistent with other code in the module.
</blockquote></details>

Done.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 63 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-KpsnypwRvK_wR061A0n:-KptfkpyMpiJz3T63P60:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/ac17b35d387867458440115d8275a8fc82457779/Tests/TestHelpers/CommonTestHelper.psm1#L63)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Change to `System.String` To be consistent with other code in the module.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/118)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/118#-:-KpxtL9JM50xcs1tAvlD:bnfp4nl)*

**Pull request merged**
