### PR TITLE
xClusterQuorum: Added the filesharewitness option.

### LINKED ISSUE #35: xClusterQuorum: Test-TargetResource fails on Windows Server 2016 using NodeAndFileShareMajority
Using the following configuration the quorum is set correctly. But in subsequently calls to Test-TargetResource, the call fails with error 'Unknown quorum resource: File Share Witness'. 

```
xClusterQuorum ClusterConfigureQuorum
{
    IsSingleInstance = 'Yes'
    Type = 'NodeAndFileShareMajority'
    Resource = "\\fileserver.company.local\clusterwitness$" 
    PsDscRunAsCredential = $installCredential 
}
```

This is because when evaluating it uses the following code

``` 
elseif ($ClusterQuorum.QuorumResource.ResourceType.DisplayName -eq 'File Share Witness')
{
    $ClusterQuorumType = 'NodeAndFileShareMajority'
}
```

But the property `DisplayName` is actually set to 'File Share Quorum Witness'. The property `Name` and `ResourceType` is set to 'File Share Witness'.

```
PS > $ClusterQuorum.QuorumResource

Name               State  OwnerGroup    ResourceType      
----               -----  ----------    ------------      
File Share Witness Online Cluster Group File Share Witness

PS > $ClusterQuorum.QuorumResource.ResourceType

Name               DisplayName              
----               -----------              
File Share Witness File Share Quorum Witness

PS > $ClusterQuorum.QuorumResource.ResourceType.DisplayName
File Share Quorum Witness
````

So either we change so that we evaluate the property `Name`, or we change evaluation to look for the correct DisplayName. If I look at the properties in the GUI, then the Type is set to 'File Share Quorum Witness'. So I guess that correlates to the DisplayName property, and Name can be changed by the user. So I guess we need to change to the correct display name string value.

image

### PR DESCRIPTION
**Pull request by Blankf**
**Pull Request (PR) description**
added the option of the filesharewitness
https://technet.microsoft.com/en-us/itpro/powershell/windows/failoverclusters/set-clusterquorum#-filesharewitness

This option was not possible yet with the xClusterQuorum module.

**This Pull Request (PR) fixes the following issues:**
Fixes #35 

**Task list:**
- [ x] Change details added to Unreleased section of CHANGELOG.md?
- [ x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ x] Examples appropriately updated?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/141)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for this PR! For me to be able to review and merge this you need to sign the CLA (see comment above). If you did sign it and it hasn't reflected here (changed the labels), let me know. 

Also, FileShareWitness did already exist with the 'NodeAndFileShareMajority' option, but there is an issue with it on Windows Server 2016, and I think you are trying to solve that (see issue #35). So, if you could please change this PR to resolve issue #35 for the 'NodeAndFileShareMajority' option. Thank you!

**Comment by Blankf** [comment]
changed the commens on the PR, did not match that one to my PR.

**Comment by johlju** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/141#-Ksdk0NVzMQIIW0i9hds:-Ksdk0NVzMQIIW0i9hdt:b-q0jzsz) ([raw file](https://github.com/powershell/xfailovercluster/blob/04fbed4e5d087fe1cccb58e760ed0ea8e030aeb8/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.schema.mof#L5)):*
> "FileShareWitness"

There is already an option for this. 'NodeAndFileShareMajority'. So there is no need to add a duplicate option. :)

Instead, please change this PR so it fixes issue #35, it currently does not. Please read issue #35.

Thank you! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/141)*

**Comment by johlju** [comment]
@Blankf did have a chance to look at my previous comment?

**Comment by Blankf** [comment]
Hi @johlju, sorry missed it, i guess you mean this comment:

`There is already an option for this. 'NodeAndFileShareMajority'. So there is no need to add a duplicate option. :)`

it may be doing the same thing, but i find it confusing to deviate from the technet documentation which says Filesharewitness and aliases to NodeAndFileShareMajority.

i can see if i can rewrite the module later.

**Comment by johlju** [comment]
I guess the TechNet article you mention is the one in the PR description? I understand what you mean, but the options is choosen (my guess) from this [TechNet artice](https://technet.microsoft.com/en-us/library/cc731739(v=ws.11).aspx) under the section 'Quorum configuration choices', and was not choosen from what the PowerShell cmdlet parameters was named.

**Comment by johlju** [comment]
Another option would to add the cmdlet parameter names as options too, duplicating all of them, but I don't like that option. It doesn't add any value. I instead rather change the README.md to add to the parameter description that the options are sometimes referred to the other names as well.

**Pull request closed without merging**
