### PR TITLE
xClusterPreferredOwner: Enabled localization

### LINKED ISSUE #86: xClusterPreferredOwner: Localization should change to align with HQRM modules
**Details of the scenario you tried and the problem that is occurring:**
Resource should use the same method of localization as HQRM modules (PSDscResource).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xClusterPreferredOwner
  - Enabled localization for all strings ([issue #86](https://github.com/PowerShell/xFailOverCluster/issues/86)).
  - Fixed typo in the returned hash table from Get-TargetResource.

**This Pull Request (PR) fixes the following issues:**
Fixes #86 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/117)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO do you have time to review this one for me? No hurry.

**Comment by PlagueHO** [comment]
No problem @johlju - will review tomorrow night after work (bed time now!)

**Comment by PlagueHO** [comment]
@Johlju - I figure you're going to be correcting the other issues to meet standards later on, so I didn't comment on anything outside the changes you made (it was difficult to resist the urge though :grin: )
 
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/117#-:-KpsrJ_S2Lkmtlmy-w7l:b8ligkr)*

**Comment by johlju** [comment]
@PlagueHO Actually I already run this thru "basic" style change cleanup. So please. if you see stuff I missed, then please comment on them, because then there is something I overlooked.
I keep this PR open if you want to comment more. 😄 

All resources should go through more detailed cleanup later. Planing creating an issue for each style guideline "rule" and fix all resources per issue later on, so this module can get to HQRM. But can we squash some things now, then that is even better.

**Comment by PlagueHO** [comment]
@johlju - actually, it was mainly comments querying why there were brackets around things that don't seem to need them. But everything else is OK!
```powershell
$null = (Get-ClusterGroup -Cluster $ClusterName) |  .....
```

**Comment by PlagueHO** [comment]
Anyway...

:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/117#-:-KpxswJkSV5vq-QKUORM:b-yniy7i)*

**Comment by johlju** [comment]
@PlagueHO Aha, I missed those, or looked passed them because of other style changes. I will fix those in another PR, and go thru all resource at the same time :)

Big thanks for reviewing! 😄

**Pull request merged**
