### PR TITLE
xClusterQuorum: Refactor unit test

### LINKED ISSUE #47: xClusterQuorum: Missing an example for this resource
We should add an example for the resource xClusterQuorum.

### LINKED ISSUE #53: xClusterQuorum: Script Analyzer warnings that need to be fixed
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xClusterQuorum.psm1 (Line 26): $null should be on the left side of equality comparisons.

### LINKED ISSUE #57: xClusterNetwork: Missing an example for this resource
We should add an example for the resource xClusterNetwork.

### LINKED ISSUE #77: xClusterQuorum: Unit tests does not use the correct template and folder structure is wrong
**Details of the scenario you tried and the problem that is occurring:**
Unit tests does not use the correct template and folder structure is wrong

I suggest change so the correct template is used for the unit tests, and that the correct folder structure is used.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xClusterQuorum
  - Refactored the unit test for this resource to use stubs and increase coverage
    (issue #77).
  - Changed the code to be more aligned with the style guideline.
  - Updated parameter description in the schema.mof.
  - Added example (issue #47)
    - 1-SetQuorumToNodeMajority.ps1
    - 2-SetQuorumToNodeAndDiskMajority.ps1
    - 3-SetQuorumToNodeAndFileShareMajority.ps1
    - 4-SetQuorumToDiskOnly.ps1
  - Added links to examples from README.md.

**This Pull Request (PR) fixes the following issues:**
Fixes #53 
Fixes #47 
Fixes #77 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/104)

### CODE REVIEW

**Comment by johlju** [comment]
@bgelens Whenever you have time to review again 😉
Not much more code coverage by this refactoring, but hopefully I covered more scenarios. And found a bug again.

**Comment by johlju** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 106 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-KoY2KTW7q1J-25qGsNq:-KoY2KTW7q1J-25qGsNr:b97b7mr) ([raw file](https://github.com/powershell/xfailovercluster/blob/25cd5502e6467901aece2690fd54a8687447d303/CHANGELOG.md#L106)):*
> ```Markdown
>   - Changed the code to be more aligned with the style guideline.
>   - Updated parameter description in the schema.mof.
>   - Added example (issue #57)
> ```

This is the wrong issue number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104)*

**Comment by johlju** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 106 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-KoY2KTW7q1J-25qGsNq:-KoYC7N6hQVYjtW8h6Yz:big0p9j) ([raw file](https://github.com/powershell/xfailovercluster/blob/25cd5502e6467901aece2690fd54a8687447d303/CHANGELOG.md#L106)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This is the wrong issue number.
</blockquote></details>

Done. Updated to the correct issue number 47.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104)*

**Comment by johlju** [comment]
Closing and reopening to kick of AppVeyor tests.

**Comment by johlju** [comment]
Closing and reopening to kick of AppVeyor tests. This after AppVeyor deployed a temporary workaround.

**Comment by johlju** [comment]
@PlagueHO do you mind to review this one if you have a chance?

**Comment by PlagueHO** [comment]
@johlju - will get onto this tonight after work! A pleasure to help!

**Comment by PlagueHO** [comment]
@Johlju - looking pretty good. Only some minor queries...

---

Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 48 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5qtJn3cpGOomsPMX:-Kpc5qtK1zik7Hr17Kgg:bj0m817) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L48)):*
> ```PowerShell
>             $clusterQuorumType = 'NodeMajority'
>         }
>         'NodeAndDiskMajority' {
> ```

Please add blank line above this line.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 51 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5tLeu8xK9fMcm6Bk:-Kpc5tLeu8xK9fMcm6Bl:bj0m817) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L51)):*
> ```PowerShell
>             $clusterQuorumType = 'NodeAndDiskMajority'
>         }
>         'NodeAndFileShareMajority' {
> ```

Please add blank line above this line.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 68 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc61oSEi3pdYwzhpJb:-Kpc61oTYBfAFH86OE9_:b-76t9ra) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L68)):*
> ```PowerShell
>     if ($clusterQuorumType -eq 'NodeAndFileShareMajority')
>     {
>         $clusterQuorumResource = $getClusterQuorumResult.QuorumResource | Get-ClusterParameter -Name SharePath | Select-Object -ExpandProperty Value
> ```

Can you split this line to make it easier to read? E.g.
```powershell
$clusterQuorumResource = $getClusterQuorumResult.QuorumResource |
    Get-ClusterParameter -Name SharePath |
    Select-Object -ExpandProperty Value
```

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 75 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5uNIfp0xHbPyrft_:-Kpc5uNIfp0xHbPyrfta:b7w3c) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L75)):*
> ```PowerShell
>     }
> 
>     @{
> ```

Not a blocker but I think it is clearer to always include `return`.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 182 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc6LJm333xT4iQ4g46:-Kpc6LJn4sAQwcHDqmBm:bxtkojh) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L182)):*
> ```PowerShell
>     }
> 
>     $testTargetResourceReturnValue
> ```

I think it is clearer to include a `return` - but not a blocking issue.

---

*[Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1, line 8 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc6Z7UNEMiSsnL01TB:-Kpc6Z7UNEMiSsnL01TC:b-9c0nac) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1#L8)):*
> ```PowerShell
>     This example assumes the failover cluster is already present.
> #>
> ```

Can we remove blank line? We don't usually include them between <# #> and `function` so I reckon it doesn't make sense to include them between <# #> and 'Configuration`. Not a blocker.

Also occurs in all other examples.

---

*[Tests/Unit/MSFT_xClusterQuorum.Tests.ps1, line 344 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc80_RJzmkchRYvxra:-Kpc80_RJzmkchRYvxrb:b-la6dms) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/Tests/Unit/MSFT_xClusterQuorum.Tests.ps1#L344)):*
> ```PowerShell
>             }
> 
>             Context 'When the system is not in the desired state' {
> ```

Is this meant to be here? Seems to have no actual tests defined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-:-Kpc8H3V3wSzvKCUElPl:bfc1h8j)*

**Comment by johlju** [comment]
Review status: 8 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 48 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5qtJn3cpGOomsPMX:-KpeTExAsFu8SSDGHIPl:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L48)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please add blank line above this line.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 51 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5tLeu8xK9fMcm6Bk:-KpeTFaYkIvKRcSUtJp8:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L51)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please add blank line above this line.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 68 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc61oSEi3pdYwzhpJb:-KpeTSx66z-KKGUyWu66:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L68)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you split this line to make it easier to read? E.g.
```powershell
$clusterQuorumResource = $getClusterQuorumResult.QuorumResource |
    Get-ClusterParameter -Name SharePath |
    Select-Object -ExpandProperty Value
```
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 75 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5uNIfp0xHbPyrft_:-KpeTUX_UOQIL54bOn0T:b-tdorhi) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L75)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not a blocker but I think it is clearer to always include `return`.
</blockquote></details>

I tend to agree. I normally do that. But @bgelens like us to not use it unless it it is used to exit a code path. So all other resource are not using 'return' for these. 
So I rather keep this as-is as is to be consequent.
If we get a guideline to use return for these, then we change them back. :) I saw Katie asked to get return on these as well in a PR in another repo.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 182 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc6LJm333xT4iQ4g46:-KpeUU6-c2E3c4s28Rz6:bhrsg0f) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L182)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think it is clearer to include a `return` - but not a blocking issue.
</blockquote></details>

Se previous comment.

---

*[Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1, line 8 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc6Z7UNEMiSsnL01TB:-KpeUbORkN1USTp52Zld:b-spc9qu) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we remove blank line? We don't usually include them between <# #> and `function` so I reckon it doesn't make sense to include them between <# #> and 'Configuration`. Not a blocker.

Also occurs in all other examples.
</blockquote></details>

I rather keep these :/ It's makes the text easier to read, to have paragraphs, especially in another example file, with more text.
And Katie and Mariah is using blank rows in there comment-based help

Example 1: https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_WindowsOptionalFeature/MSFT_WindowsOptionalFeature.psm1#L345-L353

Example 2: https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1#L118-L178

---

*[Tests/Unit/MSFT_xClusterQuorum.Tests.ps1, line 344 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc80_RJzmkchRYvxra:-KpeVIJ2MDKAp0v-OjiV:b-896fix) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/Tests/Unit/MSFT_xClusterQuorum.Tests.ps1#L344)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is this meant to be here? Seems to have no actual tests defined.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104)*

**Comment by johlju** [comment]
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[Tests/Unit/MSFT_xClusterQuorum.Tests.ps1, line 344 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc80_RJzmkchRYvxra:-KpeVe6ZsJSg9mM8kb8w:b-9oc9gi) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/Tests/Unit/MSFT_xClusterQuorum.Tests.ps1#L344)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done. The Get-TargetResource will always return a value (single instance resource), so there is no "in desired state" and "not in desired state". I was expecting to be able to put tests here, but when I saw it wasn't possible I forgot to remove this context-block. 
The previous context-block is named accordingly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1, line 75 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc5uNIfp0xHbPyrft_:-KpgA2TE5T7xAGpnTt2x:b-bav16t) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I tend to agree. I normally do that. But @bgelens like us to not use it unless it it is used to exit a code path. So all other resource are not using 'return' for these. 
So I rather keep this as-is as is to be consequent.
If we get a guideline to use return for these, then we change them back. :) I saw Katie asked to get return on these as well in a PR in another repo.
</blockquote></details>

See comments from other PR. All good! 

---

*[Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1, line 8 at r3](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-Kpc6Z7UNEMiSsnL01TB:-KpgACdpgY8bwbaawPD6:bh1tflb) ([raw file](https://github.com/powershell/xfailovercluster/blob/6a457db434a5b3265be583b5bbe3d5d4d6bbd97d/Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I rather keep these :/ It's makes the text easier to read, to have paragraphs, especially in another example file, with more text.
And Katie and Mariah is using blank rows in there comment-based help

Example 1: https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_WindowsOptionalFeature/MSFT_WindowsOptionalFeature.psm1#L345-L353

Example 2: https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1#L118-L178
</blockquote></details>

All good! No worries! :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104#-:-KpgALWra_ToCEFGPvbk:bnfp4nl)*

**Comment by johlju** [comment]
Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/104)*

**Pull request merged**
