### PR TITLE
xClusterRoleProperties: Configure Cluster Role Properties

### PR DESCRIPTION
**Pull request by jmos5156**
Allows the configuration of Cluster Role Properties

**Pull Request (PR) description**
Allows the configuration of Cluster Role Properties

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfailovercluster/162)

### CODE REVIEW

**Comment by johlju** [comment]
@jmos5156 Could you please add unit tests to this? Also add this resource to README.md.

**Comment by johlju** [comment]
@jmos5156 Let me know if you need any help with this PR.

**Comment by jmos5156** [comment]
Hi johlju Any help greatly appreciated. A bit new to this whole process... I do have some updates

**Comment by johlju** [comment]
No worries. Happy to have you here! 😄 Thanks for contributing! 
Let's start with this PR, it's seems as the smallest of them you have sent in.

For me to be able to merge this need to be fulfilled

* An entry in the CHANGELOG.md
* Code should follow the [style guidlines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#make-code-changes).
* Documentation updated in README.md
* A unit test that test the resource.

What do you say, should we take it from the below steps (see review comments below), and then build from there? I will help you along the way. **Let me know if you want help with any of these step. Happy to help!**

And please do push more commits (code changes) if you have an update to this PR. And if you don't know how it works, then it's easy. Just push commits to the same working branch as this PR is based on (xClusterRoleProperties in your fork of xFailOverCluster), and this PR will update.

---

Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QqYCsJ0qBjiWHggtY:-L2QqYCsJ0qBjiWHggtZ:b-e6xurx) (no related file):*
Can you add an entry to the Unreleased section of the CHANGELOG.md?

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2Qqbg81g2AUc-ULlJD:-L2Qqbg81g2AUc-ULlJE:b-gpaun3) (no related file):*
If there is no existing issue that cover this new resource, then please create a new issue for this PR? Please reference the issue in the PR description text under "*This Pull Request (PR) fixes the following issues*".

This is because discussions around a subject are normally made in issues.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QqdJOdv1EqVACmS4a:-L2QqdJOdv1EqVACmS4b:b-3w0wuq) (no related file):*
Can you add an example in the Examples folder (create a new folder for the new resource)? See an existing resource for example.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QqrcBzPldBpngZY6A:-L2QqrcCfuAoERtEMGrO:b-6lw7gk) (no related file):*
Can you document the resource in the README.md? See an existing resource for example.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QsKq9tlltH4ggJGt4:-L2QsKq9tlltH4ggJGt5:b-ozq6f5) (no related file):*
Please change the parameters in the code to match the style guidline. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

There are a few more style changes that need to resolved, but lets start with just this one, and I review again once these review comments are resolved.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QuXl2svJ_LAgDFm8s:-L2QuXl2svJ_LAgDFm8t:b-h6bo4e) (no related file):*
Add unit tests that tests this resource. See other unit tests for example, and the [test guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).

---

*[DSCResources/MSFT_xClusterRoleProperties/MSFT_xClusterRoleProperties.psm1, line 13 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2Qv3epey9dZlNO8Vmf:-L2Qv3epey9dZlNO8Vmg:balobh8) ([raw file](https://github.com/powershell/xfailovercluster/blob/8f7faf70e6ecc501b588394993aa056e2b597ddf/DSCResources/MSFT_xClusterRoleProperties/MSFT_xClusterRoleProperties.psm1#L13)):*
> ```PowerShell
>         [Parameter(Mandatory = $false)][string] $Priority,
>         [Parameter(Mandatory = $false)][UInt32] $FailoverThreshold,
> 		[Parameter(Mandatory = $false)][UInt32] $FailoverPeriod,
> ```

Seems you are using tabs. Please change your editor to use 4 white spaces instead of tabs.

---

*[DSCResources/MSFT_xClusterRoleProperties/MSFT_xClusterRoleProperties.schema.mof, line 4 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QvbY__MAcQpLflk22:-L2QvbY__MAcQpLflk23:b-25xobc) ([raw file](https://github.com/powershell/xfailovercluster/blob/8f7faf70e6ecc501b588394993aa056e2b597ddf/DSCResources/MSFT_xClusterRoleProperties/MSFT_xClusterRoleProperties.schema.mof#L4)):*
> key

Please change to 'Key' (upper 'K'). Same for the next parameter that uses key.

---

*[DSCResources/MSFT_xClusterRoleProperties/MSFT_xClusterRoleProperties.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-L2QvNsAxO-z08R-fkBU:-L2QvNsAxO-z08R-fkBV:bt6tw10) ([raw file](https://github.com/powershell/xfailovercluster/blob/8f7faf70e6ecc501b588394993aa056e2b597ddf/DSCResources/MSFT_xClusterRoleProperties/MSFT_xClusterRoleProperties.schema.mof#L5)):*
> ```
> {
> 	[key, Description("Name of the Role to configure")] 
> 	string Name;
> ```

Please move the type and name to the previous row.
```
[Key, Description("Name of the Role to configure")] string Name;
```

Throughout this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xfailovercluster/162#-:-L2QqMwxrsFOu6_aetpu:b-yxlh1d)*

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by johlju** [comment]
Closing this PR due to inactivity. If there are someone who wants to work on this issue or PR please open a new PR.

**Pull request closed without merging**
